var scramblesMap = {
    "1": [
        "L' R' U R' B R U L'",
        "U R B' U L' U' L' R' B'",
        "U' L R' L U' B' U B' L'",
        "U' R' L U' R' U' B R' U",
        "U' R' L' B U' R' L U R'",
        "B U' B R L' R B' U L",
        "L' U R B R U' L U' L",
        "L' R' U B U R L U' L",
        "U B L B L U R L B' R'",
        "U R B U' L' U' L B R' B'",
        "U R' L B' L' R' U L B' R",
        "U' L B' L R B' L R' U L'",
        "U' L R B' R B' R' L U L'",
        "U' L' U L R' L R B U' R'",
        "U' L' U R' U B U' R U L'",
        "B U' R' L' U' B L R B' R",
        "B R L' U L B L' B' R' U'",
        "B R L' R' U' B' L' B L R",
        "B R L' R' U' R L U R' U'",
        "B R' B' U L' U B R' U' L"
    ],
    "2": [
        "R L U' L B' L' U' R",
        "U L R B' U L R' U' L",
        "U L R' U L U B' L U'",
        "U R' L R' U B U' B R",
        "U' L' B U' R U R L B",
        "B' U B' L' R L' B U' R'",
        "R U' L' B' L' U R' U R'",
        "R L U' B' U' L' R' U R'",
        "U R U' L U' B' U L' U' R",
        "U R U' R' L R' L' B' U L",
        "U R' B R' L' B R' L U' R",
        "U R' L' B L' B L R' U' R",
        "U' B' R' B' R' U' L' R' B L",
        "U' L R' B R L U' R' B L'",
        "U' L' B' U R U R' B' L B",
        "B U R L U R' U B R' U",
        "B U R' B L R' L U R U",
        "B R' B' L' U L U' B R' B",
        "B R' L' B L' B' U L R' B",
        "B' U L R U B' R' L' B L'"
    ],
    "3": [
        "R B' U' B' R B' R B",
        "U B R B R U' R B' U'",
        "B L' B' U R U' B L U",
        "L' U B' L U R B' L U",
        "R L B' L B R' B R' U",
        "R' U B' U B' R' B' U' B",
        "R' U B' R' B' U' B' R B",
        "R' U' R B' L R' B' U L'",
        "U B U' R' U B U R' B' U'",
        "U R' B L' B L R' L' B' L",
        "U R' L B R' L' B R' B' L",
        "B U R' L' R' L' U' L' R' U'",
        "B L B' L' B' L R' B' R U",
        "B' U B' R' B' R B L U L'",
        "B' U R' U' B L U L' B U'",
        "B' U' L U' L R B' R L' R",
        "B' L' U' B U B U L' U' R",
        "B' L' U' B L' U' L B L R",
        "B' R' B' L R U L U R' L'",
        "L U R U R' B U R' U L"
    ],
    "4": [
        "L' B U B L' B L' B'",
        "U' B' L' B' L' U L' B U",
        "B' R B U' L' U B' R' U'",
        "L U L' B R' L B U' R",
        "L U' B U' B L B U B'",
        "L U' B L B U B L' B'",
        "L' R' B R' B' L B' L U'",
        "R U' B R' U' L' B R' U'",
        "U' B' U L U' B' U' L B U",
        "U' L B' R B' R' L R B R'",
        "U' L R' B' L R B' L B R'",
        "B U R' U R' L' B L' R L'",
        "B U' B L B L' B' R' U' R",
        "B U' L U B' R' U' R B' U",
        "B L B R' L' U' R' U' L R",
        "B R U B' U' B' U' R U L'",
        "B R U B' R U R' B' R' L'",
        "B' U' L R L R U R L U",
        "B' R' B R B R' L B L' U'",
        "L U' B' U' B' U L B U L'"
    ],
    "5": [
        "U' B' R' U R B' L B",
        "R L B' R L' B' L' B",
        "R' U' L' U L R L B'",
        "U' B L' U B' U' L B' L'",
        "U' L' U L' B' L R L' R'",
        "L' B R L R' L' B' L' B'",
        "R' L' R L B R' B' L' B'",
        "U B' U R' L R' L' U R U'",
        "U R B' L R U' L R' U' R'",
        "U' L' U' L' R' L R B' R' U'",
        "B R U R B' L' U B' R' L'",
        "B' L' R' B' U R' B' L' U B'",
        "B' R U' B U' L' B L B R'",
        "B' R U' R' L' U L R U R'",
        "B' R B U B' U R' L R' L'",
        "L' B U R' U' L' R' L R B",
        "L' B L' U' L' R B U R' L",
        "L' B L' R L B' U B' U R'",
        "L' B' R' U' R U' R' U' R U'",
        "L' R U R' U B' L U' L' R"
    ],
    "6": [
        "U B L U' L' B R' B'",
        "L U R U' R' L' R' B",
        "L' R' B L' R B R B'",
        "U B' R U' B U R' B R",
        "U R U' R B R' L' R L",
        "L R L' R' B' L B R B",
        "R B' L' R' L R B R B",
        "U R U R L R' L' B L U",
        "U' B U' L R' L R U' L' U",
        "U' L' B R' L' U R' L U L",
        "B L' U B' U R B' R' B' L",
        "B L' U L R U' R' L' U' L",
        "B L' B' U' B U' L R' L R",
        "B R L B U' L B R U' B",
        "B' L' U' L' B R U' B L R",
        "L U B R' B U' R' L' B' R",
        "L U R B U' B' R' U' L' B",
        "L R' B U L B' L' R' U' B",
        "L R' B' L' U' R' B R U B",
        "L' U' L' B' R' L U' B' L' U"
    ],
    "7": [
        "R L' U' B' L' U R U",
        "R' L U L U' R B' U'",
        "R' L' B L' R' U L B",
        "B L R' U' R U L' R B",
        "L U L' U B L' R L' B",
        "R L U L U R' B' U' R",
        "R L U R L' B' R' L U",
        "U L R L' R' U B L R B",
        "U L' U' R' U R' U' B' L' U'",
        "U L' R B R U' L B U R",
        "U L' R' L B L' U B' L B'",
        "B U L U' R U' B' R U' B'",
        "B U' L U' B U' L' R U' R",
        "B U' R' L' U' B R L U' L",
        "B R' L' B' U R B' L U' L",
        "B' L B L' R U' R L' B' R",
        "L U R' L R L U' L' B' U'",
        "L U' R' U' B' R U' L R U",
        "L R B' R L' U L' R' U' L",
        "L R L U' R U B' L' U' L'"
    ],
    "8": [
        "L R B' R L U' R' B'",
        "L R' U' R' U L' B U",
        "L' R U B R U' L' U'",
        "B' R' L U L' U' R L' B'",
        "L' R' U' L' R B L R' U'",
        "L' R' U' R' U' L B U L'",
        "R' U' R U' B' R L' R B'",
        "U' R U L U' L U B R U",
        "U' R L R' B' R U' B R' B",
        "U' R L' B' L' U R' B' U' L'",
        "U' R' L' R L U' B' R' L' B'",
        "B R' B' R L' U L' R B L'",
        "B' U L R U B' L' R' U R'",
        "B' U R' U B' U R L' U L'",
        "B' U' R' U L' U B L' U B",
        "B' L R B U' L' B R' U R'",
        "L B R U' L' U' L' R U L'",
        "L B R U' R' U' B' L' B U",
        "L' U B L U L' U' L' R U'",
        "L' U B' R' L' R U' B' L' R'"
    ],
    "9": [
        "U R U L R B' R L",
        "U' R' L U' B' L' R' L'",
        "U B R' U B' U' L' B' L'",
        "U L B U R L' B U' L'",
        "U' L B R' U' B U R L",
        "U' R' B' U' R B L' B' L",
        "B' R' B U B R' B' L' B'",
        "L B R B U' L' U' L U",
        "U L U B' U' R U' R' U' R",
        "U L' R B' R U L R U L",
        "U L' R L U' B' R' L' R U",
        "U' B R L R L' R L B U",
        "U' B R' U L U' L R' B R'",
        "U' B' L' R' B' U' R L' B L'",
        "U' R' L U' L R' L' R' B' R'",
        "U' R' L R L B R L B U",
        "B U L' U B U' R' L R' U'",
        "B L' R' U' R L' R U B R'",
        "B R L' B' R' B' U L U' R",
        "B' U B R B U' R B' L' B'"
    ],
    "10": [
        "U L R' U B R L R",
        "U' L' U' R' L' B L' R'",
        "U L B U L' B' R B R'",
        "U R' B' L U B' U' L' R'",
        "U' B' L U' B U R B R",
        "U' R' B' U' L' R B' U R",
        "B L B' U' B' L B R B",
        "R' B' L' B' U R U R' U'",
        "U B R L B U L' R B' R",
        "U B' L U' R' U R' L B' L",
        "U B' L' R' L' R L' R' B' U'",
        "U L R' U R' L R L B L",
        "U L R' L' R' B' L' R' B' U'",
        "U' R L' B L' U' R' L' U' R'",
        "U' R L' R' U B L R L' U'",
        "U' R' U' B U L' U L U L'",
        "B U R B U' B L B U R'",
        "B U R B L B U B L' R'",
        "B U' B' L' B' U L' B R B",
        "B L B L' U' L B' R L' U'"
    ],
    "11": [
        "U L' U R' L U' L R B' R'",
        "U L' U' L' U' B' R' U' R' U",
        "U L' U' L' U' R U' R' U' B'",
        "U R' B' L B' R' B' L' U' B'",
        "U R' L U' R' B R U' B U'",
        "U' B' R L' U L' R' L R L",
        "U' L B L R B' U B' U' R'",
        "U' R B L' U' R' L B R U'",
        "U' R' U' R U B' R L' U L",
        "B U' L' U B' R U R' L B'",
        "B U' R' U' B R L U' R' L",
        "B R' L B' L' U R B' R L'",
        "B' L B R L R B U B L'",
        "B' R' B' L R' B L' U L U",
        "L B' U' B' R' B U B L B'",
        "L B' R L' R' U R' L R U'",
        "L R U R U' R B U B L'",
        "L R B R B U R' U R L'",
        "L R' B' U B' L B L U' R'",
        "L R' L' U R' B L' U' R B"
    ],
    "12": [
        "U B L' R U' R L R' L' R'",
        "U L U L' U' B L' R U' R'",
        "U L' B' R U L R' B' L' U",
        "U R' B' R' L' B U' B U L",
        "U' L B R' B L B R U B",
        "U' L R' U L B' L' U B' U",
        "U' R U R U B L U L U'",
        "U' R U R U L' U L U B",
        "U' R U' L R' U R' L' B L",
        "B L B R' L B' R U' R' U'",
        "B R' B' L' R' L' B' U' B' R",
        "B' U L U B' L' R' U L R'",
        "B' U R U' B L' U' L R' B",
        "B' L R' B R U' L' B L' R",
        "L' U L' B' L U' R L R B'",
        "L' B' L' U L' B L R B R'",
        "L' B' R L U L' B R' U' B",
        "L' R' U B R' B R' U B' R",
        "R B L' R' U L' R B' U' B",
        "R L' B' U' R B' U L R' L"
    ],
    "13": [
        "L U L' B' U' L' B' R L'",
        "L U' R B L U L R' L'",
        "U B' L R' U' L B' U' R U",
        "U B' L' U B' L' R U R U'",
        "U R' B' U' R' L U' L' U' B'",
        "U' B L U' R L U' R' U L'",
        "U' B L' R' U L U' R L U'",
        "U' L R' L' U R' B L' U L",
        "B L' B' U' L R U' B U R'",
        "B L' B' L' R U B' L U B'",
        "B R B' R' L B' R B' R L'",
        "B R L' U' L U R' B L' B'",
        "B R' L' B U' B' L R U' R",
        "B' L U' R' U' B L' R U B",
        "B' L' B U' L' B R B' U B",
        "B' R' B R B' R U B' U R'",
        "L U' L' U R' B R' L' R L",
        "L U' R L' R U' B U L' U'",
        "L B' R U L' B' L' B U B'",
        "L B' R B L' U' B R' U' R"
    ],
    "14": [
        "R' U L' B' R' U' R' L R",
        "R' U' R B U R B L' R",
        "U B' R L U' R' U L' R' U",
        "U B' R' U L' R' U L U' R",
        "U R' L R U' L B' R U' R'",
        "U' B R U' B R L' U' L' U",
        "U' B R' L U R' B U L' U'",
        "U' L B U L R' U R U B",
        "B L B' L' B L' U' B U' L",
        "B R B' U R B' L' B U' B'",
        "B R' U L U B' R L' U' B'",
        "B' L R B' U B R' L' U L'",
        "B' L' B L R' B L' B L' R",
        "B' L' R U R' U' L B' R B",
        "B' R B U R' L' U B' U' L",
        "B' R B R L' U' B R' U' B",
        "L R B L' R L' U' L' B U'",
        "L R L' U L U' R' L B' U'",
        "L' U B R' U B R' U' L' U",
        "L' U L R' L' B' R L U' R"
    ],
    "15": [
        "U L' U L' B' L' R U' B'",
        "R U L' B U L R' L R'",
        "U B L' U L' U' L B' R' B",
        "U B L' B L' B' R U' R' U",
        "U B R' L' U L' U' R L U'",
        "U B' L B L' U B U R L",
        "U L' U' L R' L' U L U' B",
        "U' B L U' B L' U' L B' R",
        "U' R B' R B R' B R' U' R",
        "B L' B' R B' L' R' L' B' L'",
        "B R' L' B U B' R L U' R'",
        "B' U L R' B' R' U' L' U' L'",
        "B' U' R' U' B R' B' R U' B'",
        "B' R U' R' U R' B U R' B",
        "B' R B U' R B U' R U' R'",
        "B' R' L B U R' U B U' L'",
        "L B U B' R U' B' U' B' L",
        "L B U' R' B U' L' B' R U",
        "L B R B R L U B' L' U",
        "L R B R B L B' U R U'"
    ],
    "16": [
        "U' R U' R B R L' U B",
        "L' U' R B' U' R' L R' L",
        "U B' R' U B' R U R' B L'",
        "U L' B L' B' L B' L U L'",
        "U' B R' B' R U' B' U' L' R'",
        "U' B' L R U' R U L' R' U",
        "U' B' R U' R U R' B L B'",
        "U' B' R B' R B L' U L U'",
        "U' R U R' L R U' R' U B'",
        "B U L U B' L B L' U B",
        "B U' R' L B L U R U R",
        "B L R' B' U' L U' B' U R",
        "B L' U L U' L B' U' L B'",
        "B L' B' U L' B' U L' U L",
        "B' L R B' U' B L' R' U L",
        "B' R B L' B R L R B R",
        "L B' U' L B' U' B L' U L",
        "L B' L U L' R L' R' L U'",
        "L R' U R U' B' R L' R' L",
        "L' U' R L' B' U R' L' R' U'"
    ],
    "17": [
        "U L U R' L U B' U' L",
        "U R' B R' L' R U B U",
        "U' B' R' U R' U' L' U L",
        "L U' B U L' U B R' L",
        "L U' L' B L' R' B U' R'",
        "R L U' R B' R B' U B",
        "R' U R' B' U' R' U L' U",
        "R' L R' U' L' U L B' L'",
        "U B U' B' R' L' U' B' U' L'",
        "U' B' L' B' L B U R' L R",
        "U' R' U' R U' L' B' R U' R'",
        "B U L R B U' L R' L U",
        "B L R' L R' B U R' U' R'",
        "B L' B R U' B' U' R' U B",
        "B R' L' U B U' B U B' L'",
        "B' U' L' R L' R' L' R U' R'",
        "L U' B' L' U L' R U L' U",
        "L U' R' L R' B' U L' U R",
        "L' R B' L R B' R' B R' L",
        "L' R' B L' R L' R L' B L"
    ],
    "18": [
        "U B L U' L U R U' R'",
        "U' L B' L R L' U' B' U'",
        "U' R' U' L R' U' B U R'",
        "L U' L B U L U' R U'",
        "L R' L U R U' R' B R",
        "L' R' U L' B L' B U' B'",
        "R' U B' U' R U' B' L R'",
        "R' U R B' R L B' U L",
        "U B R B R' B' U' L R' L'",
        "U L U L' U R B L' U L",
        "U' B' U B L R U B U R",
        "B U R L' R L R L' U L",
        "B' U' R' L' B' U R' L R' U'",
        "B' L R U' B' U B' U' B R",
        "B' R B' L' U B U L U' B'",
        "B' R' L R' L B' U' L U L",
        "L U L' R' L U' R' L' B U",
        "L R L R' U' R U B U R",
        "L R' L' U B U' R' U R L'",
        "L' U L' U' B U B' R L' B"
    ],
    "19": [
        "U B L' B' L' B R' U' R'",
        "U B' L' U B U' L B R",
        "U L' R U L' U R L' B",
        "U' R' B R B' L' U' B L'",
        "B U L B U' B' U L' R",
        "B L' B U' B' U' L' R L'",
        "L' B' L B' R' U B' L' B",
        "R U R' L R' U L' B L",
        "U L' R B' U L' R L' B' L",
        "U L' R B' L' U R L' R B'",
        "U R L' B R' B U' L R' B'",
        "U' B' L' U' B' L' U' L' U R",
        "U' B' L' U' B' R B R' B' L'",
        "U' L R U R U L' B' R' B'",
        "U' R' B R U B L' U' B' L",
        "U' R' L R B' L R U' B' U",
        "B L R' L B' R B R L U",
        "B L' B U R' B U' R' L' B",
        "B' L' R B L U' B L R' L'",
        "L U L' B U R U' L' U' R'"
    ],
    "20": [
        "U L B' L' B R U B' R",
        "U' B R U' B' U R' B' L'",
        "U' B' R B R B' L U L",
        "U' R L' U' R U' L' R B'",
        "B' U' R' B' U B U' R L'",
        "B' R B' U B U R L' R",
        "L' U' L R' L U' R B' R'",
        "R B R' B L U' B R B'",
        "U B R U B L' B' L B R",
        "U B R U B R U R U' L'",
        "U L B' L' U' B' R U B R'",
        "U L R' L' B R' L' U B U'",
        "U R' L' U' L' U' R B L B",
        "U' L' R B' L B' U R' L B",
        "U' R L' B U' R L' R B R'",
        "U' R L' B R U' L' R L' B",
        "B R L' B' R' U B' R' L R",
        "B' R B' U' L B' U L R B'",
        "B' R' L R' B L' B' L' R' U'",
        "L U' B R' B U L' R' L R'"
    ],
    "21": [
        "U R' B' R' U' L B' R U'",
        "U R' L R' U L' R B L",
        "U' L' R L B' L B U B",
        "B U R' B' L B L' U L",
        "L' B R' U' R' U' B' R B",
        "R U L R' L' R U' B U",
        "R U' R L B L B U' B'",
        "R B' R L' B R' U B L",
        "R' U' B' U' R L B' R U'",
        "R' L' B' L' B' U B U B'",
        "U B' U B' R' L' B L B' U",
        "U L U R' U' B U' R' U L'",
        "U L' B' L B' R' U R L' R",
        "U' L' R B' U B R B' R B'",
        "B U R L' U' B L' B' L R'",
        "B U' L' U' L' B R' B R B",
        "B R' L' B L B' U' R U' L",
        "B' U L' R L U B' L' R U'",
        "B' U' L' B L U' L' B L R",
        "B' L U' R' U L B' R' L R"
    ],
    "22": [
        "U R L' R' B R' B' U' B'",
        "U' L B L U R' B L' U",
        "U' L R' L U' R L' B' R'",
        "B' U' L B R' B' R U' R'",
        "L U B U L' R' B L' U",
        "L R B R B U' B' U' B",
        "L' U L' R' B' R' B' U B",
        "L' U' R' L R L' U B' U'",
        "L' B L' R B' L U' B' R'",
        "R B' L U L U B L' B'",
        "U R L' B U' B' L' B L' B",
        "U' B U' B L R B' R' B U'",
        "U' R B R' B L U' L' R L'",
        "U' R' U' L U B' U L U' R",
        "B U R B' R' U R B' R' L'",
        "B U' R L' R' U' B R L' U",
        "B L' U' R' B U' R B' U B",
        "B R' U L U' R' B L R' L'",
        "B' U R U R B' L B' L' B'",
        "B' U' L' R U B' R B R' L"
    ],
    "23": [
        "B R U' B R' B' L U B",
        "B' R U' B U' R' L' B' L",
        "B' R U' B R U' L' R' B'",
        "L B R' B' U' B' R' U R'",
        "L R L B R' L B R' L'",
        "L' U L B R' B' L' U' B'",
        "L' U' L R L U B U' B",
        "R B U' R L R' L' B U",
        "R L B L' U B' U B' L",
        "R L R B' U B' U R' B",
        "U L' B' L R L' U' B' L B",
        "U R U' B R L' B' R' B' R",
        "U R U' L' B L U' L' B U'",
        "U R L U' R' U L B' R' U'",
        "U R' U B L' R' B U' R' L",
        "U' R L' B' U B' U' L B U",
        "B L' B' R' B U B R' U R'",
        "B L' R' B' R' U B R' U B",
        "B R' B U L' R' U' R U' L",
        "B R' L R' L R' B' L B' R"
    ],
    "24": [
        "B L' U B' U L R B R'",
        "B L' U B' L' U R L B",
        "B' L' U B' L B R' U' B'",
        "L' B' U L' R' L R B' U'",
        "L' R' B' R U' B U' B R'",
        "L' R' L' B U' B U' L B'",
        "R U R' L' R' U' B' U B'",
        "R U' R' B' L B R U B",
        "R' B' L B U B L U' L",
        "R' L' R' B' L R' B' L R",
        "U L' R B U' B U R' B' U'",
        "U' L U' B' R L B' U L R'",
        "U' L' U B' L' R B L B L'",
        "U' L' U R B' R' U R B' U",
        "U' L' R' U L U' R' B L U",
        "U' R B R' L' R U B R' B'",
        "B L' R U L' B' L' B L' U",
        "B R B R' B' L B' R' L' B",
        "B' L B' U' R L U L' U R'",
        "B' L R' L R' L B R' B L'"
    ],
    "25": [
        "U R U L' R B R L",
        "U R U R L B L R'",
        "B U' B' L R L' B U'",
        "U B L U' L B' R' B U",
        "U L R B U L' B U' B'",
        "U L' B U' B L' B' R U L'",
        "U L' R' U R' U B' U B' U",
        "U R L U L R B R' L R'",
        "U R' U B R' U L U R U",
        "U' B' R' B U R' L B R' L",
        "U' L U' B' U R U R L' B'",
        "U' L' B' L U' B' L R U R",
        "U' R' U' L U B R' B' U B",
        "U' R' L' U R' U L U' B U",
        "B L B U R' B' U' L R' L'",
        "B' L U R' U' L U' B' L R",
        "L U R U' R' B' U L' B' R",
        "L B L' R U B L B' R L",
        "L' U' B R' B R' U' R' B' U'",
        "L' B' U L U R B' R' U L'"
    ],
    "26": [
        "U' B U R' U' L U' R",
        "B' L' U' B' R' U' R' U",
        "B' L' U' R U' R' U' B'",
        "B' U' R' L U' L R B' R'",
        "B' R' U' R' B' L U' R L",
        "U R' L' R B U' R U L' U'",
        "U' R' B' U' L U B R' U B",
        "B U L B' L' R U' B' U B'",
        "B L U B' R U' B' U B' R'",
        "B L R L' B' R' U B R' L'",
        "B R L R' B U R' U' B' U'",
        "B R' L R L' U' B' U' B L",
        "B' L R' L' U B' L' U' L' R'",
        "B' L' B' U' R' L' R' L R' U",
        "B' R B U' R L' R L' B R'",
        "B' R L' U R' B R L' R' B",
        "L U' R' B L' B R U' R B'",
        "L R' U L' B U R' L' R U'",
        "L' U B L' B' U R' L U' B",
        "L' U L R' B U' R L' R' U"
    ],
    "27": [
        "U R' B' R' U' L' U' L'",
        "L B' R U' R' B L B'",
        "R' U' B' U' R L' U' L'",
        "B L B' R L' B' U' R' L'",
        "L' B' U B R' L R' B' L'",
        "U R' U B' U' R' L' R' U' L'",
        "U R' U' L U' L B' R L U'",
        "U R' B U L B' L' B' R U'",
        "U' B R L' B U L U' L' R'",
        "U' B R' L' U B R' U L' U",
        "U' L' U' R' B L R' B R L",
        "U' R' B L R' L U L' R' B",
        "B R U' L' U' L' B L R' L",
        "B' L' B U B' L' R' L U L",
        "B' R' U' R' U' B L U' B' U'",
        "L B U L U B' U B' L R",
        "L' U' L' R' L' U B' L' U L'",
        "L' B L' B L' U L' U R L'",
        "L' B' L R' L' U L' R U L",
        "R U R' L B U L' B' R' B'"
    ],
    "28": [
        "U' L R' L U L' B' L",
        "B L U L U' L R B",
        "L' U L U B L R B",
        "U B U' R' L R' U L B",
        "R' U' L R' B U L U B",
        "U B L' B L U' B L' R' B'",
        "U B' R U' R U' L B' U' B",
        "U R L R B L' R U R' B",
        "U' L' B' U' R' L R' U L' U'",
        "B U' L U' B' R B' U L R'",
        "B L U' R L U L R' B U",
        "B L' B L U' R B R' L' B'",
        "B' U R U' B' U L' R U' B",
        "B' U R' U L U' B' U' B R",
        "B' U R' L' B' L' U L B R",
        "B' U R' L' R U R L R' U'",
        "B' L R U' L' R' U R' U R",
        "B' L R' U L' B R B' L' R",
        "B' L' U B' L' R' L B U L",
        "L U' R U L' B' R L' U R'"
    ],
    "29": [
        "L U' L U' R' L U' B",
        "L R' U B' R U' B' L",
        "R B' U' L U' B L' B",
        "U B R' L R' B' U R' L' B",
        "U L R' L R B L R U' L",
        "U L' B U L R U R L R'",
        "U R' U B' U' B L' B L R'",
        "U R' L' U' B' L U' B' R' U'",
        "U' B L U' L U' L' R U R'",
        "U' L U B' U' R L' B U' B",
        "U' R' L' B' U R' L' R' B' U",
        "B' U L R' L' B L' U B U'",
        "B' L B' L' U R' B U B' L",
        "B' L' U' L U' R' B' U' R' L",
        "B' R U R L B U B R' U",
        "B' R B U' R L' B' U B' U",
        "B' R' U B R' L' R B U' L",
        "L U B' L B U R L' U B",
        "L U' B R' B U' B' R L U'",
        "L R B U' R B L' B L B"
    ],
    "30": [
        "U R' L' U R B' R U'",
        "R L' U' L U R' B' U",
        "R' L R' L B R' U' B",
        "U B L' U' L' R B L R",
        "B L B U B' R' L' R B",
        "R B' U' L' R B U' B' U'",
        "R' B' L' U R U' R' L' U",
        "U B U' L B U L' R' L' R'",
        "U B L B U' L R' L' R' U'",
        "U B L' R' U B R U' L' R'",
        "U R U' R B' L' R L' R' U",
        "U' L U R' U B L B L R",
        "U' L B' U' R' B' L' B' L B'",
        "B L B U' L U R' U' L' U'",
        "B L B R U B L' U L B'",
        "B L B' L R' U' L B' U' L",
        "B R' U L U L B L U' R",
        "B' L R' L U' B U B' U' L",
        "B' L' U' B' R B L B' R B",
        "B' L' B' U B R B' L' R B"
    ],
    "31": [
        "L' R U L' R L' B L'",
        "R' U R' U B' R L B'",
        "R' L U' B R L' R L'",
        "U B' R' U B L' B R' U' R",
        "U L R' L' U L B' U' R B'",
        "U L' U' B' R' U' B' U' L R'",
        "U L' R' U R' U R L' B R'",
        "U R U B' U R U L U B'",
        "U R' B U B' R B' R' L B'",
        "B U' R' L U' B U B' L' U",
        "B L U L B' R L U B R'",
        "B R' L' U L U' L U' R L'",
        "B' U' L U' B R L' U B L'",
        "B' L U B L U' R U B R",
        "B' L R' L R B' R U' R' U",
        "B' R L' U' L' B' R' L' R' U",
        "B' R' U B' U' B' L' B' R B'",
        "L R U B L' B' L R L B",
        "L' U B U R L B' U B U",
        "L' B U' B' U B U' L' R U"
    ],
    "32": [
        "B U' R L' U' B R L'",
        "B' U R L' B' U B R'",
        "L' U B R' B' U B' R",
        "B R U R' U' L B U R'",
        "B' R L B R' B' R U R",
        "L' B' L B L B' U' L' U'",
        "R' U' L' B' L R L U' L'",
        "U' B R U' R' B R' L R' U",
        "U' B R B' R U B' U L' U'",
        "U' B' R L' B' L U R B R'",
        "U' L' R U' B' L' R' B L' B'",
        "B U L U L' B U' L' U' L'",
        "B U' R U B' U' L' B' U R",
        "B L U' L R U' L' B L' R'",
        "B L B L B' L' B U' L' U'",
        "B L B' R' B' U R' U' L U",
        "B R L' B' R' U' R U B' R",
        "B' U B R B L' B' U R' B'",
        "B' L R L' R U R' L R' L'",
        "B' L' R L' U' L R U' L R"
    ],
    "33": [
        "U B' L B' R' B R' B' U R",
        "U R' U R L R L' B U L",
        "U' B' L U L' R L B' U R'",
        "U' L U L' U' L' B U' R L",
        "B U' R U L' U' L U' R' U",
        "B L B U' B U L U R' B",
        "B R B' L U' R' B' R U B'",
        "B' R B L' B R B' U' B U'",
        "L U' B' L R' U' L R B' L",
        "L' U' B U' L R L R' L' R",
        "L' B' L' R B' L' B' L' B R'",
        "L' R L' B' R U B' U R L'",
        "R U' L' R B R L' U L' U'",
        "R B L' R' U R' B' U L' B",
        "R' U L' R U B' R U L' B'",
        "R' B R' L' R' U' L U' R' U'",
        "U B L' U B L' U' B L R' B",
        "U B L' B U L' U' L B R' B",
        "U B R' U L' R B' R' B' L' B'",
        "U B' L U' B' L' B L' B' U' R"
    ],
    "34": [
        "L' R' B U B U L' B'",
        "R B L' U' B' R' B L",
        "U B' L' U' R B' L' R L'",
        "U B' R' U R' L' R U' B'",
        "B' U L R' U L B' R L",
        "B' U R U L' B L U' B",
        "L U' L R L' U B U R'",
        "L B' U L B R B' U B'",
        "L' U R' L U R U R' B",
        "L' U' R B' R' U B' L' U",
        "R U L' B R L' R U R'",
        "R U' R B' L' B' L' U L'",
        "R' B R' B' L' U' B R' L",
        "R' L U' R' B L' R' L' U",
        "U R' B L U B R L B' U",
        "U' B R' B' U' L U R' U B",
        "U' L B L' B U' R L' B' L",
        "U' R' U R' U' B U' L' U' L'",
        "U' R' B' L' U' B R L B L",
        "B U' L B U R' B' L R' L'"
    ],
    "35": [
        "L B R B' L' B'",
        "U' B L R' B L' U' L",
        "L B L' B' R' B' L R",
        "R' U' L U L R L' B'",
        "L U' B U' B' R B L B",
        "L' R' L' U' L U L' R B'",
        "U B L B L' R U' L' U' L'",
        "U B' L R L R' L' R' U L'",
        "U L B L' U' R' B' L R B'",
        "U' B U B' U' L' R' L' U' B'",
        "U' B U B' U' R' U' L' B' U'",
        "U' L' R' B' R U B L R B'",
        "U' R L' R U L' R U' B' R",
        "U' R' U' B' R L' U L R L",
        "U' R' U' L' R L U' L' B' U'",
        "U' R' U' R L U R' B' L R",
        "U' R' L' U' B R' B' U' R B'",
        "B U' L R' U' L' B' R' B' U'",
        "B U' L R' B U R U L R",
        "B U' R' L' U' B' U R' B' U'"
    ],
    "36": [
        "R' B' R' L U R",
        "B U' R' U L' B R U'",
        "L R L' B' L' R' U R",
        "R' B' L R U B U' B'",
        "R B R L U' B' U B' R",
        "R' L R' L U R' B' U' R'",
        "U B' U R' L' B U' R U B'",
        "U L U R' L' R U' B' U R'",
        "U L' U L' R U' B' R L' R",
        "U L' B L U L' R' L' U' B",
        "U' B L U B L B' R B L",
        "U' B R' U L' R' B' R' U' B'",
        "U' B R' U R U L R B L",
        "U' L' B' U R' U' R' L' U' L",
        "U' L' B' L' R' B' L' B U' L",
        "U' L' R' B' L' U' L' U R U'",
        "U' L' R' B' R B R' B' L' U'",
        "U' L' R' L' U' B' R' B R B'",
        "U' L' R' L' R L U' L' U' B'",
        "U' R' U' B' U' R U L U R"
    ],
    "37": [
        "U' B' U R' L' B' L R' L",
        "L' B R' U' R' B R B' L'",
        "U B R' L R L' B' U' B U'",
        "U L R B' L' B L' U' B U'",
        "U R L' B U' B L' R' U B'",
        "U' B' U' R U' L' R' B' R' L",
        "U' B' U' R U' R L' B' L' R'",
        "U' L U R U R' B L' R' U'",
        "U' L' B R' B L' U R U B'",
        "U' R L B R' B L B U B",
        "U' R' U L R' L' B R U R'",
        "U' R' U L' U L B R' L' R",
        "U' R' L' R B R' L R U' R",
        "B R B' U R L' B' R' L B'",
        "B R B' L U' B' L' U R B'",
        "B R' B L B' L' U R' L R'",
        "B' U L B' U R' U' L U L'",
        "B' U' R' L U' B' U L' R' L'",
        "B' L U' B L' R' L' B' L' B'",
        "B' R' B U B R' L R L' U'"
    ],
    "38": [
        "U B U' L R B R' L R'",
        "R B' L U L B' L' B R",
        "U B U L' U L' R B R L",
        "U B U L' U R L B L R'",
        "U L U' R U' R' B' L R L'",
        "U L U' R' L R B' L' U' L",
        "U L R L' B' L R' L' U L'",
        "U L' R' B' L B' R' B' U' B'",
        "U R B' L B' R U' L' U' B",
        "U R' U' L' U' L B' R L U",
        "U' B' L R' L' R B U B' U",
        "U' L' R B' U B' R L U' B",
        "U' R' L' B R B' R U B' U",
        "B U L R' U B U' R L R",
        "B U' R' B U' L U R' U' R",
        "B L B' U' B' L R' L' R U",
        "B R' U B' R L R B R B",
        "B' L B' R' B R U' L R' L",
        "B' L' B U' L' R B L R' B",
        "B' L' B R' U B R U' L' B"
    ],
    "39": [
        "B U L' R' L R B L' U",
        "B' L R' L R L B' R B",
        "U B U B L R U' L U' R",
        "U B' L B U B' R' U L' R'",
        "U L R' B L' B L' U L' U'",
        "U L' B' U B R B' U L' R'",
        "U R L' U' B' R L' U R' U",
        "U R' U R B' R U' B L' B'",
        "U R' U' L' U L' B L' U B",
        "U' R' B' U' R' L U' B' L' B",
        "B U R' B L B L R B' U",
        "B U' R L' R U' B R L' U'",
        "B L R L' R L R' L B R",
        "B L' U' B' R' L U R B' L",
        "B R' L' B R U' B U' B' R",
        "B' U' B L' R' L R L B' U",
        "B' L B R L R L' B R B",
        "B' L R' B' L' U L' U B U",
        "B' L' R L B' R B L R' L'",
        "L U' B' R' L R B' U' L B"
    ],
    "40": [
        "B R' L R' L' R' B L' B'",
        "B' U' R L R' L' B' R U'",
        "U L B U L R' U B R B'",
        "U' B R' B' U' B L U' R L",
        "U' B' U' B' R' L' U R' U L'",
        "U' L U R U' R B' R U' B'",
        "U' L U' L' B L' U B' R B",
        "U' L' R U B L' R U' L U'",
        "U' R B U' B' L' B U' R L",
        "U' R' L B' R B' R U' R U",
        "B U B' R L R' L' R' B U'",
        "B R L' R' B L' B' R' L R",
        "B R' B' L' R' L' R B' L' B'",
        "B R' L B R U' R U' B' U'",
        "B' U L' R L' U B' L' R U",
        "B' U' L B' R' B' R' L' B U'",
        "B' L R B' L' U B' U B L'",
        "B' R U B L R' U' L' B R'",
        "B' R' L' R L' R' L R' B' L'",
        "L U R U' L B' U L' B' U'"
    ],
    "41": [
        "B' L' R U' R' L U'",
        "U' R U' B' R L' U' R U'",
        "L' R' U' R B' L' R U' L",
        "L' R' L U R' B' R' L' U",
        "R U' L' R' U' B L' B U'",
        "U B L B' L U' B' L R' L'",
        "U R' L' U' R B' R' U R U",
        "B L U' L B' R B L B U",
        "B R U L' B' U R' L B' U'",
        "B' U R' U R' L R U' L' R",
        "L U R B' R U R L U' L",
        "L B U' B L' U B R' L' B'",
        "L B R U' L' R' L U' B L'",
        "L B' R U B' R' U' L' B L",
        "L B' R U' R' L B' U' B U",
        "L B' R' L U R' U R' L' U",
        "L' U B L U' R' U L' B R'",
        "L' U B' L' U' L R L R L'",
        "L' U L U' R B' L' R U R'",
        "L' B' L R U' R' L B' U B"
    ],
    "42": [
        "B R L' U L R' U",
        "U L' U B L' R U L' U",
        "L' U R L U B' R B' U",
        "R L U L' B R L' U R'",
        "R L R' U' L B L R U'",
        "U' B' R' B R' U B R' L R",
        "U' L R U L' B L U' L' U'",
        "B U' L U' L R' L' U R L'",
        "B' L' U' R B U' L R' B U",
        "B' R' U R' B L' B' R' B' U'",
        "L U L U L R' B R L R'",
        "L U R B' R' B R' L' B U'",
        "L' U L R L' U B L R U",
        "L' U' B' U B L' B L R U'",
        "L' U' B' U B' R L U R' U",
        "L' B U' B L U' B' R U' R",
        "L' B' L' B R U R' L U' B",
        "R U' B R U R' L' R' L' R",
        "R U' B' R' U L U' R B' L",
        "R U' R' U L' B R L' U' L"
    ],
    "43": [
        "U L' U B U' L R",
        "U B' U R B' U L R' U",
        "U R' L U' B R B U B'",
        "U' R B U B L' B' U L",
        "B' U B' L U R' L U L",
        "U L R L U B' L R U B'",
        "U L' R L R U' L B' U' B'",
        "U R L' U B' L R U' B' R'",
        "U' B R' B' L B' L' B U B",
        "U' B' L' U' R' B L' B L' R'",
        "U' B' R U B' L U R' U L'",
        "U' L' R' U L U' R B L U'",
        "U' R B U B' U L B' U' B'",
        "U' R B L' U R' U' R U L'",
        "B U' R U' L' U B U' R B'",
        "B L' U L' U R U R' U' L'",
        "B R U' R B U' L U' B' U'",
        "B R' L' U' B' U' L U B L",
        "B R' L' B' L' R B U R' L",
        "B' U L' U' L' R' L R' B' L'"
    ],
    "44": [
        "U' R U' B' U R' L'",
        "U L' B' U' B' R B U' R'",
        "U' B U' L' B U' R' L U'",
        "U' L R' U B' L' B' U' B",
        "B U' B R' U' L R' U' R'",
        "U B L' U' B R' U' L U' R",
        "U B R U L B' R B' R L",
        "U B' L B R' B R B' U' B'",
        "U L' B' U' B U' R' B U B",
        "U L' B' R U' L U L' U' R",
        "U R L U' R' U L' B' R' U",
        "U' L' R U' B R' L' U B L",
        "U' R L' R' L' U R' B U B",
        "U' R' L' R' U' B R' L' U' B",
        "B U' R U R L R' L B R",
        "B L' U' R' U L' B' L' U' B'",
        "B R B' U' B' L' U L U' R",
        "B' U L' U R U' B' U L' B",
        "B' L R U B U R' U' B' R'",
        "B' L R B R L' B' U' L R'"
    ],
    "45": [
        "B' U' L' R U R' L U",
        "L' B L U' B U' R' L",
        "U R L' U' R' L' U B' R'",
        "R B' U' R' U L R L U",
        "R' U L' B' U L U' R' U'",
        "U L' R' L R L U' R B' L'",
        "U R B' U R' B' L' B R L'",
        "U R' L' R L' U' B R' B U",
        "U' B L' U B' U L U R' B'",
        "U' B' L U' R B R' B R' B",
        "U' L B' R B' R' U' B U L",
        "B U' R' L R U' L' B L' U",
        "B L' B' R' B L' U L' B U",
        "B R' B' U' R B' U' L R L",
        "B' U R' L U R' L' R U' R",
        "B' U' B' R L U' R U L' B",
        "B' L U B U L U' L' R' B'",
        "B' L R U' B R' U' B R' B",
        "L R B' U R' U' R U' L' U",
        "L R L' B L U L' B U L"
    ],
    "46": [
        "B U R L' U' L R' U'",
        "R B' R' U B' U L R'",
        "U' L' R U L R U' B L",
        "L U' R B U' R' U L U",
        "L' B U L U' R' L' R' U'",
        "U B R' U L' B' L B' L B'",
        "U B' R U' B U' R' U' L B",
        "U R' B L' B L U B' U' R'",
        "U' L R L' R U B' L B' U'",
        "U' L' B U' L B R B' L' R",
        "U' R L R' L' R' U L' B R",
        "B U B L' R' U L' U' R B'",
        "B U' L R' U' L R L' U L'",
        "B R' U' B' U' R' U R L B",
        "B R' L' U B' L U B' L B'",
        "B' U L R' L' U R B' R U'",
        "B' L B U L' B U R' L' R'",
        "B' R B L B' R U' R B' U'",
        "L U' L' R' L' R U R' B R",
        "L B' L U B R' L' B U' R'"
    ],
    "47": [
        "U L U' R L B' U' L'",
        "B L' R' L R' L B R'",
        "U L U R B L' U' L' B",
        "U' B' U' L B R' L' U B'",
        "L' B' L U' R' L' U' R U",
        "U B U' R B' L' R B' R' U",
        "U B R' U B' R L' B' R' L",
        "U B' L U L R' L' B R' B'",
        "U L' U L' B' U R L' U' L",
        "U L' R' L U' B' U R' L R",
        "U' L' R' U' L R' L U' R' B'",
        "B U B L' R' B' L R' B U'",
        "B U B R' U B R B' L R",
        "B U B' L B R' U' B' L B'",
        "B L R U' B' L U' L' B' L",
        "B L R' U B' U L' B' L' R",
        "B R' L' U R L' B L' U R'",
        "B' L U R' B' R' B L' R U",
        "B' R' U' L' U L B' R L B",
        "B' R' B U' R' L U R U B'"
    ],
    "48": [
        "U' R' U L' R' B U R",
        "B' R L R' L R' B' L",
        "U B U R' B' L R U' B",
        "U' R' U' L' B' R U R B'",
        "R B R' U L R U L' U'",
        "U R L U R' L R' U L B",
        "U' B R' U' R' L R B' L B",
        "U' B' U L' B R L' B L U'",
        "U' B' L U' B L' R B L R'",
        "U' R U' R B U' L' R U R'",
        "U' R L R' U B U' L R' L'",
        "B L U R U' R' B L' R' B'",
        "B L B' U L R' U' L' U' B",
        "B L R' B L' B' L' U R U'",
        "B R' U' L B L B' R L' U'",
        "B' U' B R' B' L U B R' B",
        "B' U' B' L U' B' L' B R' L'",
        "B' U' B' R L B R' L B' U",
        "B' L R U' L' R B' R U' L",
        "B' R' L U' B U' R B R L'"
    ],
    "49": [
        "L' U' R L' R U R B'",
        "U B U' B' R' L R' B' R'",
        "B' L' R' U' R' L' R' L' U'",
        "R U' B U R U' L B L'",
        "R' U B' L' B' L' R U' B",
        "R' U R B U' L' U B U",
        "R' B U R' U B' L' R' B'",
        "R' L' R' L U L R' B' R'",
        "U B L' U R' U R' B' R B'",
        "U B' U L B U' B U B L",
        "U' B L' B L B R' L B' R'",
        "U' B' L' R B L B' R' L R",
        "U' L U B' U B U' L' U B'",
        "B L U' L B L B U B' U",
        "B L' U' L R L' B' R U B'",
        "B L' B' L' B U' L B L U'",
        "B R' L U R' U' L' U B L'",
        "B' U' B' U B' R' L B R B",
        "B' U' R B U' L U B' R' U",
        "B' L U' L' B' U' B' L' B' L"
    ],
    "50": [
        "L U' R' U' B L' U B",
        "U L' R' U B' R' U' L R'",
        "B L U L U B L R U",
        "B' U' R' L R U' R' L' R",
        "L U B R L' B R' U' R",
        "L' U B' L U R U L' R",
        "R L U B' L' B' L B R",
        "R L U B' R U R U' L'",
        "U L U R L' B R U' L B",
        "U L' U' R U B L' U' B U'",
        "U R' U B' L' B' U' L R B",
        "U R' U R' U R' U B' U R'",
        "U R' U' R B' R U' R U' R",
        "U R' B U L R' B' L' B' R",
        "U R' B L U' R' U' R' L B",
        "U' B' R' B L' U B R' L B",
        "U' L B R L R L B R' U",
        "U' L' U' L' R L' U' B' U L'",
        "U' L' U' R' U B' U' R' L R'",
        "U' R' U R' L' U L' B' L' R'"
    ],
    "51": [
        "R U L' U R' L' B' R",
        "U R B U L R B R L",
        "B' U' B U L U' B R B",
        "L U R L' R' U' B R B",
        "L B' L' R B' L U B R",
        "L R' U' B' U R L' U' L'",
        "L R' L B L B U' L R'",
        "L' U B' R' U' L U' L' U",
        "U B U B' U L U' R' B' R'",
        "U B L' R' U L' R' B R L'",
        "U L' B' R U' R B U' B' R",
        "U R U L R U' R B L' B",
        "U R B U L' R L B L R'",
        "U R B L' U R L B R' L",
        "U R' L U B U L R B U'",
        "U' L U' L' U R U B' L' U",
        "U' R U B' L' U L R' L' R",
        "U' R L R B' U R' U' R' L",
        "U' R' L U' L' U' B' L' U L'",
        "B U R B' L' R' U L U' B'"
    ],
    "52": [
        "R' L B L U' B L' R'",
        "U B L U' B' L R U B'",
        "U' R' L' B' L' R' U' R' L'",
        "B' R B U' B U R U' B",
        "L' B' U' L B' U' R' B U",
        "L' B' U' L R B U' R' B'",
        "R U' B R' U' R' B' U B'",
        "R' L' U' R' L R' U L B'",
        "U B' R U L B R B' R L",
        "U L' R B U L' U' R' U' B",
        "U L' R' L' U B' L B U B'",
        "U R B' R L B' L R U B",
        "U R' L' B U L' B L U' L'",
        "U' R U' B U' B U' R U' R",
        "U' R B U B' L U' B' R' L",
        "U' R L U' R' B L B' U B'",
        "U' R L' R' B' R' L U' R' L'",
        "U' R' L B' L R B U B' R'",
        "U' R' L R U' B R' L' R B",
        "B U L B' R B' U' L U' R'"
    ],
    "53": [
        "U B U R L U B' U B' L",
        "U' L' B' U R U B L B' U'",
        "U' L' B' L' B' L R B U L",
        "B U B' R B R' U' B U' L'",
        "B L' B U' B' R B' U B' U",
        "B R L R' U' R B L' R' L'",
        "B' R' U L' R U' L' U' L' U'",
        "B' R' B L R U' R' B L' B",
        "L B U B U B' R' B' R' B'",
        "L B U L' B' L' B' L' U R",
        "L' B' U' L' U' L' B R' L B'",
        "R B L' R L' U L B L R",
        "R B R' U' R' L U L' B L'",
        "R' U B' L R B' R L' B R'",
        "R' B' U' R U B' L' R U B",
        "R' L' B L' U' L R U' R B",
        "U B' U' B' U' L B U L U R",
        "U B' U' B' R L R B U R U'",
        "U B' L B R' L' U' L B R B",
        "U B' L' U B' R U' R' L' B L'"
    ],
    "54": [
        "U B' U R' U' L R L B' L'",
        "U L U B' L' R L U' L' B'",
        "U R B' R L B' L' B R' B'",
        "U' B R' B R' U' L' R' B' R'",
        "U' R' B' L' U' B U B U R",
        "B U' L B' U R U R B U",
        "B L B L B R' B' R' B' U'",
        "B' U B' L R L' U' B' L B",
        "B' L' R L' U' R U B' U L",
        "B' R' L' U B R' L' R B L",
        "L B' U L' B L' U' B R' L",
        "L' U' B' U' R' U L' U B' L'",
        "L' R' U B U B U R' B' U'",
        "R U R U R L' U R' L B",
        "R B U' B' R' L' R' B U R",
        "R' B R' B L' B R B' U B'",
        "U B' U B' R L U' R U' L U",
        "U B' U L R L' B R' U B R'",
        "U L U B R L' U L R L U",
        "U L U' L B R U' L R L' R'"
    ],
    "55": [
        "U L U R L' U R B",
        "B' R' L' R' L B' U' L'",
        "L B U B' L B R U",
        "R' B' U' R B' R' L' R'",
        "U B L B U' B' U R L U",
        "U B' U' B U L R U R B",
        "U B' U' B R' B' U' B' L' R'",
        "U B' R' L B' U' B' R B U",
        "U L R U R B U' L U R'",
        "U R L U' B' U' R B' L' U",
        "U R L B L' U' L R' U' L'",
        "U R' L' R U' B L' U' R L",
        "U' B L R' B' R' L' B' U' B'",
        "U' B R B U B U L B U'",
        "U' L' U' R B' L' U B' L' U'",
        "B U' L' R' U' L' U' L' U' R",
        "B U' R' U L U L U R L",
        "B R U L' B L B' R L R",
        "B' U B U' B' R' U' B' U' L'",
        "B' U B U' L B U L R U"
    ],
    "56": [
        "U L U' R U' B' R L U' B'",
        "U L' U' B' R B' L R U' L",
        "U L' R U' L R B' L B' U'",
        "U R U B' L' U' L' U B' L",
        "U R U R L U B U' R' U",
        "U R U' B' L' U B R' B R'",
        "U R' B U' L' B L U B' R'",
        "U' R' U B R U' R' L' U L",
        "B U B' R B' R' U B' L R'",
        "B U' L R L' B R U' B' L'",
        "B R' U L' B' U' L B L' U",
        "B' U L' R B' U L R' U' L",
        "B' U L' R' U L U B' L U'",
        "B' R B R' L' U' B' U' B' R'",
        "L R U L' R' L U' L' B U'",
        "L' B U' B' U' L R B U' L",
        "L' B L R' B' R L' B L' U",
        "L' B L' R' U R' U R L R'",
        "L' B' U R B U' R' L' B R",
        "L' R U' B L B L U' B' R'"
    ],
    "57": [
        "U B' R B U' L' R' B L' R",
        "U B' R B' L U' L' B R B'",
        "U L' R' L R U R U B U",
        "U' B R' U' L U' B' R L B",
        "U' B' U L' R L B' U R' U",
        "U' L R' B L R U' R' U R'",
        "B L R' L' U' L B U R' B'",
        "B' L B' L U B' R' U' B U",
        "B' L' U B R B' U' L B' U",
        "B' L' U' B' R' B' U' B L R'",
        "B' L' U' L R L U R' L B'",
        "B' R U R L' B L' B' R B'",
        "B' R B' U B' L' B L' U R",
        "B' R' L B' L U R' L' R L",
        "L' U' L U B' U' L B' R U",
        "R B' U R' B' R' B' U B U",
        "R L U' R' L' B R L R' U'",
        "R L' U R U L' B' U' R B'",
        "R L' R U R' B R' L' R' U",
        "R L' R' L B R' U R' U R'"
    ],
    "58": [
        "U R B U' L U B' U R'",
        "U' R U' R U L U R L'",
        "L' R B R B L B' U B'",
        "R U B' U' B U' R L R",
        "R L R B' R U' R' B R",
        "R' B L' U B L' R L B",
        "U B U' L B U' B R L U",
        "U B L' R B' R' B' L U' B",
        "U B' R L' R' B' L B' R U",
        "U L' R U' R' U' L B' R B",
        "U R' B R' L B' L' R L' U",
        "U' B U L' B R B' L U' B'",
        "U' R' U B L R U B' U' L'",
        "U' R' B U L B' R U R' U'",
        "U' R' B L' B R B' U L B'",
        "U' R' B R' B' R U R' L R",
        "B U L' B R' B' U' B R' B",
        "B L U L R' B' L' R' U L'",
        "B L R L U' L' U B' U' L'",
        "B R U L R' L B L' R B"
    ],
    "59": [
        "U L' U L' U' R' U' L' R",
        "U' L' B' U R' U' B U' L",
        "L B' R U' B' R L' R' B'",
        "L' U' B U B' U L' R' L'",
        "L' R' L' B L' U L B' L'",
        "R L' B' L' B' R' B U' B",
        "U B' U' R B' L' B R' U B",
        "U L U' B' R' L' U' B U R",
        "U L B' U' R' B L' U' L U",
        "U L B' L B L' U' L R' L'",
        "U L B' R B' L' B U' R' B",
        "U' B L' R L B R' B L' U'",
        "U' B' U R' B' U B' L' R' U'",
        "U' B' R L' B L B R' U B'",
        "U' L B' L R' B R L' R U'",
        "U' R L' U L U R' B L' B'",
        "B R B' U L B' U' R' B L'",
        "B R B' L' U B' U' R' U B",
        "B' U' R B' L B U B' L B'",
        "B' L U L B' U B' R' L' R"
    ],
    "60": [
        "B U L U' R' L' R B'",
        "U R L R U L' U' R U'",
        "U' B R L' B U B L U'",
        "L B U R L' U' L R B'",
        "L B' U L R' L' U R B",
        "L' U' B U B R B R' L",
        "U B' L U R U B U R' L",
        "U L B L U B' R' U' L' U'",
        "B U L R' U' R L' R' B' L",
        "B L R' B' U' B' U L B R'",
        "B R' B' L B' U R U' B U'",
        "B' R' L' R' B U R B' R B",
        "L B' U L' U' R' L R B L'",
        "L B' R L' R L R' B L' U'",
        "L R' L' B U' L U L' U B'",
        "L' U L' B' U' R' L' B' U B'",
        "L' B U' R' L' R' U B R B",
        "L' R B R' L U' B U' B U'",
        "L' R L B' U L' U' R' B U",
        "R U L' R' U R L' U L' R'"
    ],
    "61": [
        "B' U' R' U L R L' B",
        "U B' L' R B' U' B' R' U",
        "U' L' R' L' U' R U L' U",
        "R U B' U' B' L' B' L R'",
        "R' B U' R' L R U' L' B'",
        "R' B' U' L' R U R' L' B",
        "U' B R' U' L' U' B' U' L R'",
        "U' R' B' R' U' B L U R U",
        "B L R L B' U' L' B L' B'",
        "B' U' R' L U L' R L B R'",
        "B' L B R' B U' L' U B' U",
        "B' R' L B U B U' R' B' L",
        "L B L' U L R U' R' B' L'",
        "L' U R' U L' R' L U R' L",
        "L' U' R L U' L' R U' R L",
        "L' B' L R B' R U B' U' R",
        "L' B' L' B' L U B U R' B",
        "L' B' R B R' U' B U B' L",
        "R U' R B U L R B U' B",
        "R B' U L R L U' B' L' B'"
    ],
    "62": [
        "U R' L B R' U L' B'",
        "U' B' L U' R U L' B",
        "B' R B' L B R' B U'",
        "U R' B L R' B' R L U",
        "U' B U' R L U R B' L",
        "U' R' L R' L' R' L' U L",
        "B R U L' R' B R L' B",
        "B' R L' B' U B' R U' R'",
        "B' R' L' B' L R' U B' L",
        "L U' L R B R U' L B'",
        "L U' R L' B L' U' B' U'",
        "L B R' U' R' U' R U' B'",
        "R' B' L R' L R' L' B U'",
        "U L U R' U' B' R' U' L B",
        "U R L' B' R' B' U' B U B",
        "U' B' R' B L' R U R' L U",
        "U' L U' R L' R L U' L' R",
        "U' L B L' R' B U' B L U'",
        "U' L R U' L B' L' U B U'",
        "U' R U' B R' L' U B' R L"
    ],
    "63": [
        "U B R' U L' U' R B'",
        "U' L R' B' L U' R B",
        "B L' B R' B' L B' U",
        "U B' U L' R' U' L' B R'",
        "U L R' L R L R U' R'",
        "U' L B' R' L B L' R' U'",
        "B L R B R' L U' B R'",
        "B L' R B U' B L' U L",
        "B' L' U' R L B' L' R B'",
        "L B R' L R' L R B' U",
        "R' U L' R B' R U B U",
        "R' U R' L' B' L' U R' B",
        "R' B' L U L U L' U B",
        "U B L B' R L' U' L R' U'",
        "U L' U B' L R U' B L' R'",
        "U R' U L' R L' R' U R L'",
        "U R' B' R L B' U B' R' U",
        "U R' L' U R' B R U' B' U",
        "U' L' R B L B U B' U' B'",
        "U' R' U' L U B L U R' B'"
    ],
    "64": [
        "B' L R' L' U' R U B",
        "U' L U' R' U L R L U",
        "U' R B U B R' L B U'",
        "B L U R' L' R U B' R",
        "B' L R U' R' L U B R",
        "R L' B L B U B U' R'",
        "U B L' U' R' U B' R L R'",
        "U' B U' B U' R L' B L R'",
        "U' B U' L U B' R B' L' B",
        "U' R' U' L' B' U R B R U",
        "U' R' B L' R L R' L B' R",
        "B L B U L' R' L' U' B R'",
        "B L B' L U B L' R' L' B'",
        "B' U B' R' L' U' B' R' U R'",
        "B' U R' U R U' B R' L' R",
        "B' R U' B' U' L' B L B L",
        "L B R U R' L' U' L B' L'",
        "L' B U' B' U R B' R' B L",
        "L' B R U B' U' B' L' R B",
        "L' R U' L' R L U' R U' L"
    ],
    "65": [
        "B R' L R U L' U' B'",
        "U L' B' U' B' L R' B' U",
        "U R' U L U' R' L' R' U'",
        "B R' L' U L R' U' B' L'",
        "B' R' U' L R L' U' B L'",
        "L' R B' R' B' U' B' U L",
        "U B' U B' U L' R B' R' L",
        "U B' U R' U' B L' B R B'",
        "U L U R B U' L' B' L' U'",
        "U L B' R L' R' L R' B L'",
        "U' B' R U L U' B L' R' L",
        "B U' B L R U B L U' L",
        "B U' L U' L' U B' L R L'",
        "B L' U B U R B' R' B' R'",
        "B' R' B R' U' B' R L R B",
        "B' R' B' U' R L R U B' L",
        "L U' B' U L B' L R B' R'",
        "L B' R' L' R U L U' B L'",
        "L' B R L R' U R L' U' B'",
        "L' R U' B' U' R' U' L' B U'"
    ],
    "66": [
        "U R L R U R' U R' L'",
        "R L B' U B' R' U' R' B'",
        "U L B R' B U' R' U' B L'",
        "U R' B' U' R' U' L U B L",
        "U R' L R L' B' U' R' B L",
        "U' B' R' U' B R L R U' R",
        "L B' R B' L B U B U L",
        "L' B R' U' R' L' U B R B",
        "L' R U R B L' R' B' L' R",
        "R U' L' B' U' L R L B L'",
        "R U' L' R' L' B R B' U L",
        "R U' R B U L' U L' U' B'",
        "R L B R' L' R' U' B' U L",
        "R' U' B U L U R' U' R B'",
        "R' U' R' L' R B U L R B'",
        "R' B' R U L B R U' R' L'",
        "R' B' R L' R' L U L B L'",
        "R' B' R' L' R' B' L B' U R'",
        "U B U' R' U R' L B R U' B",
        "U B U' R' B L' R B U R' L"
    ],
    "67": [
        "U' L' R' L' U' L U' L R",
        "L' R' B U' B L U L B",
        "U B L U B' L' R' L' U L'",
        "U' L B U L U R' U' B' R'",
        "U' L R' L' R B U L B' R'",
        "U' R' B' L B' U L U B' R",
        "L U B' U' R' U' L U L' B",
        "L U L R L' B' U' R' L' B",
        "L B L R L B R' B U' L",
        "L B L' U' R' B' L' U L R",
        "L B L' R L R' U' R' B' R",
        "L' U L' B' U' R U' R U B",
        "L' U R B U R' L' R' B' R",
        "L' U R L R B' L' B U' R'",
        "L' R' B' L R L U B U' R'",
        "R B' L U L R U' B' L' B'",
        "R L' U' L' B' R L B R L'",
        "R' B L' B R' B' U' B' U' R'",
        "U B U B' L B L' U R' B' R",
        "U B U' B' R U' B' L' B' U B'"
    ],
    "68": [
        "U' L' R U L' R' L'",
        "U' R B L' B' R' U'",
        "B R L B R' U' B",
        "R L R B' U' L B",
        "B L U' B' L' R' L R' U'",
        "B R U' R U L R B' U'",
        "L B L R' B' U L U L'",
        "L B R' U' B L U B L'",
        "L R' U' B' L' B U R' L'",
        "R U' R' L' U' L R U' R'",
        "R B' L' B' L U B' U' R'",
        "R L B' R' U R B L R'",
        "U L' R' L U' R B' L B R'",
        "U R' U L B U' R' B' R' U",
        "U' B R L U B' U R' U' L'",
        "U' B' U' R L B R' B' U B",
        "U' B' R' U R' L U B L R'",
        "U' R B' U L R U L U B",
        "U' R B' R' L' B' R' B' L U'",
        "U' R' U L U' L' B' L R B"
    ],
    "69": [
        "U L' B' R B L U",
        "U R L' U' R L R",
        "B' L' R' B' L U B'",
        "L' R' L' B U R' B'",
        "B' L' U L' U' R' L' B U",
        "B' R' U B R L R' L U",
        "L' U L R U R' L' U L",
        "L' B R B R' U' B U L",
        "L' R' B L U' L' B' R' L",
        "R' B' L U B' R' U' B' R",
        "R' B' R' L B U' R' U' R",
        "R' L U B R B' U' L R",
        "U B U L' R' B' L B U' B'",
        "U B L U' L R' U' B' R' L",
        "U B' L' R' U' B U' L U R",
        "U L U' R' U R B R' L' B'",
        "U L R L B U R L' U B'",
        "U L' B U' R' L' U' R' U' B'",
        "U L' B L R B L B R' U",
        "U' L U' R' B' U L B L U'"
    ],
    "70": [
        "U L' U' L R' B U B'",
        "U L' B L U R B' R' U",
        "U' R B U B L' B U R'",
        "B' U R L' U' B' L' U B'",
        "L B' L R' U B U L R'",
        "L B' R' U R' U' R' U' B",
        "L R' B' R' L' B L' U R'",
        "U B' U' B' U' R L U L B'",
        "U L' U L' R' U' L U' L R",
        "U R U L B' R L' B' R' B'",
        "U' B R B' L' U L B' U' B",
        "U' L' R' L B' R U L U' B",
        "U' R U R' B' L R L' R' B",
        "U' R L' R' B' R L' U L B",
        "B' U B' L U R' L B' U R'",
        "B' L R B' L R' U' L B' L",
        "L B L' R U R' L B' R' L'",
        "L B' L' R U' B L U' R L'",
        "L B' R B' U R' B' U R' U",
        "L R' B U' B L B' U B' L'"
    ],
    "71": [
        "U' R U R' L B' U' B",
        "U L' B' U' B' R B' U' L",
        "U' R B' R' U' L' B L U'",
        "B U' L' R U B R U' B",
        "R' B L U' L U L U B'",
        "R' B R' L U' B' U' R' L",
        "R' L B L R B' R U' L",
        "U B' L' B R U' R' B U B'",
        "U L' U' L B R' L' R L B'",
        "U L' R L B L' R U' R' B'",
        "U R L R' B L' U' R' U B'",
        "U' B U B U L' R' U' R' B",
        "U' L' U' R' B L' R B L B",
        "U' R U' R L U R' U R' L'",
        "B U' B R' U' L R' B U' L",
        "B R' L' B R' L U R' B R'",
        "L U R' B U' R' B R' B R'",
        "L U' B U L' R L' B' L R'",
        "L U' B U' B U' R' B U' R",
        "L U' B U' R' B R' B R U'"
    ],
    "72": [
        "L' R' L U L R L U' L",
        "R' B U' R' U' B' R' L R",
        "U B U' R' B' L R L' U' L",
        "U B R U R' L' R B' R' L'",
        "U B R B L' U R' L U B",
        "U L U' B L R' B' R' U' R",
        "U L U' R U B' R' B L' R'",
        "U' B R L' B U R B L U",
        "U' B' U L' U' R U B R L'",
        "U' B' L' B R L B' U' B U",
        "U' B' L' B' L R U R B' L",
        "U' R U' R B' U' B L R U'",
        "U' R' L B' U B' R U B' U",
        "U' R' L' B U' R L' U' L' B'",
        "B L R' U' R L' R U B' L'",
        "B R U R L' B U B R' U",
        "B R' U' L' U L R' B U' B",
        "B' U R' U' R L R' B U R'",
        "B' U R' L' R' B R' L' R' U'",
        "B' L' R' B' U' L' B L' R' B"
    ],
    "73": [
        "L B' U L U B L R' L'",
        "R L R' U' R' L' R' U R'",
        "U B U' R U L' U' B' L' R",
        "U B R B R' L' U' L' B R'",
        "U B R B' L' R' B U B' U'",
        "U B' L' R B' U' L' B' R' U'",
        "U L R B' U L' R U R B",
        "U L R' B U' B L' U' B U'",
        "U L' U L' B U B' R' L' U",
        "U' B' U L B R' L' R U R'",
        "U' B' L' U' L R L' B L R",
        "U' B' L' B' R U' L R' U' B'",
        "U' R' U B' R' L B L U L'",
        "U' R' U L' U' B L B' R L",
        "B U' L U L' R' L B' U' L",
        "B U' L R L B' L R L U",
        "B L R' L' R U L U' L' B'",
        "B L' U L' R U B' U' R L'",
        "B L' U R L' R L' R U' B'",
        "B L' U' R U' L U R' B' R"
    ],
    "74": [
        "B L' U' B L R' B U'",
        "B' R B' U L U' B' U",
        "L B' U' R B L' U' L",
        "B' U B L' U' B' R' B U'",
        "B' R B' L' B' L' U L U'",
        "L U L U R' L' U R L'",
        "L B' R L B' U' L' B' L'",
        "L R L B U B' L' R L'",
        "L' U' B' L' R' L B U' L",
        "L' R B R' U' B U B L",
        "L' R L' U' R U L R L",
        "U L' U' L B L' B R' B U'",
        "U' B U L' U' L B R' B U'",
        "U' R L' B' R' U R B R' U",
        "U' R' B' U' L' B L' R' L' U",
        "B U' L B U B' L' R' U B'",
        "B R B L B L U R' L U'",
        "B R' U' R' L U' R' L' U' B'",
        "B' U L' B L U R U L U",
        "B' R B' L B L' B' U L B'"
    ],
    "75": [
        "U L' U' B' L' U' L",
        "U B' U' B' L' U' B U' L",
        "U L' B L' U' B' L' B' L",
        "U' R U' L R U B' L R",
        "R U B' L R U L' R L'",
        "U B' L' B' U' R' U' B R' U'",
        "U L R' U' R L R L' R' B'",
        "U L' U B' L' R' U L U R'",
        "U' B U R U' L' U B L' R'",
        "U' B L B' U' L U' B L' B",
        "U' B R U R B U L' R U",
        "U' B' R U L B R' U' B' R",
        "U' B' R' U L R B' U' B R",
        "U' L' R U L R' U' B' U R",
        "B U' B L' U L' B' U B L'",
        "B L U R' U B L' R' L' U'",
        "B' R B L R L' R' B' R' U",
        "B' R' U' R U R L' R' U L",
        "L U B' R U' R U' R U' R'",
        "L U' L' R L B L' B L' R'"
    ],
    "76": [
        "U R' B L' B' L B R'",
        "U' B L B' L' B U' R",
        "B' U L U' R' L R B'",
        "U L' R' U R U B U' R",
        "U R' B R U R U' L' R",
        "B L B U R L' U' R B'",
        "B R' B' L U B' R' L' B'",
        "B R' L B U' R' L' U' B'",
        "B' U R' L' U R B L B",
        "B' L' U' B' R L B' U' B",
        "B' R' L' U' R' B L U' B",
        "U L' U B' R' U' R' B' U' R'",
        "U R' B R' L U' L' U R L'",
        "U R' B R' L' R B R' B' L",
        "U' L R' L' U' B R L R' L",
        "U' R B R L' R U L R L",
        "U' R' B' U' R' U' B' R L' R",
        "B' L B R' B U B' R' B U'",
        "B' L' U' L R U R B' L U'",
        "B' R' B' L B L U B' R' U"
    ],
    "77": [
        "L' B L B' R' U R L'",
        "R U' L R' L' B R B'",
        "R' L R L' B' U R' B",
        "L B' U' B R L' R' U' L'",
        "L B' L U B' U' L' B' L'",
        "L R L B U L' B' R L'",
        "L' U' B' U' B R L' R' L",
        "L' B U' L' B L U B L",
        "L' R' U' B' L' U B R' L",
        "R U' L B L B R' L' B",
        "R B' R' L R L U R' B",
        "U R' B' L' U B R U' R U'",
        "U R' L' R U L B R' B' L'",
        "U' B L' B L U B' U' B' U",
        "U' B R' B L B U R' U' L'",
        "U' L U' L' U L U' L U L'",
        "B U B R L B' U R L B'",
        "B U' B L U B' U' L' U B'",
        "B R' B' L R B' L' U R' B",
        "B' L R B' L' B L' U R' B"
    ],
    "78": [
        "U' L' R B' R B R' L",
        "B' L R L' B L' U' L",
        "B U R' B' L' U R' L' U'",
        "B U' R U' R U B' L R",
        "L B' U' L' U B' R' U B'",
        "U' L R' L' B L B' L R L'",
        "U' R' B R' L R L' U B' U",
        "U' R' B' R' U' L R B L U",
        "B U' B' U' L R B L B' L'",
        "B U' R' U L U' R U B' U'",
        "B U' R' B' L R B' U B L'",
        "B R L R' U B' U' L' R' L",
        "B' U' R' B' U L R B L' B",
        "B' U' R' L' B L' U L R L",
        "B' L U L B U R U L' U",
        "B' L' U R' U B' U L B' L",
        "B' R L' B' R' L' R U' B' R'",
        "L' B' U' R B' R' U' L' U B'",
        "L' R' B L' B' L' R' U L' R'",
        "L' R' B R' U' R B' L' R' L'"
    ],
    "79": [
        "R' B U L' R B' L' U",
        "R' L U' B' R U' L B",
        "U L' R U R' L R U R'",
        "B U R B' R U R L' U'",
        "L' R' U L' R' L R' L U'",
        "U L' B R U L B' R U R",
        "U' L U' R' B' U' R B R U",
        "B L R' U' R B' L' R L U'",
        "B' L B' R' B' U' L' R' L' U",
        "B' L' B L B' U L' B R' L",
        "B' L' R' B' R' U B R U B",
        "B' R U' B R' B' L R' U B",
        "L U L R' B U L R B' U",
        "L B L R' U B' R' L U' L'",
        "L R B' U L R B U' L R",
        "L R L' B' U L' R B U' L'",
        "L R' L U' L U' L' R U' L",
        "L' U L' B U B' L U' R' L",
        "L' U' R' L B' R B L' R L",
        "L' R' U R' U R U' R U' L"
    ],
    "80": [
        "U B U' R L' R' U B'",
        "L R' U' R L' B L B'",
        "B' U B R B' U B R' L",
        "L' R B' L B' U' R B' R'",
        "L' R' B R B R' L B U",
        "U B' L B L' U' L B' L' B",
        "U R L U B U' L' R' B' U'",
        "U R L' B L' B' U R' L U'",
        "B U R' B L B' R B L B",
        "B U R' L R B L R' B R",
        "B R B R' U B R U R' L",
        "L U' R L B L B' R L R",
        "L B L U R' B R' B' U' B'",
        "L B L R U' L' B' L' R L'",
        "L R B' R B' R U' L' R B'",
        "L R' B' L' U' R' L' R' B U'",
        "L' B' R' B R' L U B U B'",
        "L' R B U' L' U B' R' L U",
        "L' R B R B' R' L B' U' B",
        "L' R L U B' L' U' R' U B"
    ],
    "81": [
        "L B' U' R L' B R U'",
        "L R' U B L' U R' B'",
        "U' R L' U' L R' L' U' L",
        "B' U' L' B L' U' L' R U",
        "R L U' R L R' L R' U",
        "U R' U L B U L' B' L' U'",
        "U' R B' L' U' R' B L' U' L'",
        "B L' U B' L B R' L U' B'",
        "B R B' R' B U' R B' L R'",
        "B R L B L U' B' L' U' B'",
        "B R' B L B U R L R U'",
        "B' R' L U L' B R L' R' U",
        "L U' B U L' R B' L R' U'",
        "L R L B R' L U' B' L' U'",
        "L R' U' L B' U L' R B R'",
        "L R' L' B' R' L U' B L U",
        "L' U L U' R L U' L' R' U",
        "L' U' B L U R B' U' R' U",
        "L' R L U' B L R' U' R B'",
        "L' R' L' U' L R' L' U R' L'"
    ],
    "82": [
        "R' L R L U' L' U L'",
        "B R B' R' L U R U' L",
        "L' R' U L' B U R' L' B'",
        "R B' R B' L' B L B R",
        "R' B L' U L' R' B' L U'",
        "R' L U' B' R' B R U' L'",
        "U L U L' U' B' R' L B R'",
        "U L R' B U R' B' L' U' L",
        "U L R' L R U L R U R'",
        "U R B L U B L' B U R'",
        "U R' L B U B' R L' U' R'",
        "U' B' L U' L U B R' U R'",
        "U' B' R' U' L U' B R' L' U'",
        "U' L' U B L' R' L' R' L' B'",
        "U' L' R' L U L U' R U L'",
        "B R L R L' B' U' L' U L'",
        "B' U L' B' U' R' B' L' R' L",
        "B' R L U' B' U B' R U' L",
        "B' R L R L B' U L' B' U'",
        "B' R' B' L' R B U' R B U"
    ],
    "83": [
        "R B' L B R' L' R' L",
        "U B U R' L' U B' L R",
        "B U' L U B U' B U' L",
        "L' U' L' U' B L B' U L'",
        "R B R' L' B R B R' L",
        "R' B R' B' R' L U R' U'",
        "U B U B L B U' B' L B",
        "U B' U B' L' B' L R L R'",
        "U' L U' B' U L R' B R' L",
        "B U R L' U R' U B R B",
        "B U' R B R' B R L U L",
        "B L B U' R U' B' R' B' U",
        "B L B R B' U' B' R' U R'",
        "B R' B' L R' L R' L R' L",
        "B' R L' U' B R U' R L R'",
        "B' R' B' U L' U' B R B U",
        "L U' L' B L B L B' U' B'",
        "L B U R' L R' L' U' R B'",
        "L B' U R' L' U' L U' R B",
        "L B' U' L' B' R' U' R U' B'"
    ],
    "84": [
        "L R' L' R' U R U' R",
        "B' L' B L R' U' L' U R'",
        "L B' R U' R L B R' U",
        "L R' U B L B' L' U R",
        "L' B L' B R B' R' B' L'",
        "R L U' R B' U' L R B",
        "U B L U R' U B' L R U",
        "U B R' U R' U' B' L U' L",
        "U R U' B' R L R L R B",
        "U R L R' U' R' U L' U' R",
        "U' L R' B' U' B L' R U L",
        "U' L' B' R' U' B' R B' U' L",
        "U' R' U' R U B L R' B' L",
        "U' R' L B' U' L B R U R'",
        "U' R' L R' L' U' R' L' U' L",
        "B U' R B U L B R L R'",
        "B L B R L' B' U L' B' U'",
        "B L' R' U B U' B L' U R'",
        "B L' R' L' R' B U' R B U",
        "B' L' R' L' R B U R U' R"
    ],
    "85": [
        "L' B R' B' L R L R'",
        "U' B' U' L R U' B R' L'",
        "B' U R' U' B' U B' U R'",
        "L B' L B L R' U' L U",
        "L' B' L R B' L' B' L R'",
        "R U R U B' R' B U' R",
        "U R' U B U' R' L B' L R'",
        "U' B U' B R B R' L' R' L",
        "U' B' U' B' R' B' U B R' B'",
        "B L B U' R U B' L' B' U'",
        "B L' R U B' L' U L' R' L",
        "B' U L' B' L B' L' R' U' R'",
        "B' U' L' R U' L U' B' L' B'",
        "B' L B R' L R' L R' L R'",
        "B' R' B' U L' U B L B U'",
        "B' R' B' L' B U B L U' L",
        "L B U L' U' L U' B' R L'",
        "L B' U' R' U' L R L' U B",
        "L B' L B L' B R B' R' L'",
        "L B' L R' L R' U' L B U'"
    ],
    "86": [
        "B R L U' R B' U' L R",
        "L U R U' L B R B' R'",
        "L U R U' R' U' L U L",
        "L B' R' L R B L R' L",
        "L' B L R' U' L' U R' B'",
        "L' B R B R' L R B R'",
        "U R B' R' U' L' R' B L U",
        "U R' L' R' U B L B' L R'",
        "U' B U' L R B' U' L' U R",
        "B U R U' B' R L R L R",
        "B L R' L' R' U R U' R B'",
        "B R' L R L U' B' R' U R'",
        "B' R L' B' R B R' B R L'",
        "L U' L' U L R' L' U R U'",
        "L B' R' L' U R' U B R U'",
        "L' U B' U' L' R' L U B L",
        "L' R' B' L R L R' L' B L",
        "L' R' L' R B U R U' R B'",
        "R U' B' L' B L B' R U' B",
        "R B R U R B U' L U' B"
    ],
    "87": [
        "U R L' B R U B' U' R",
        "L U R' U' R' B R' B' R'",
        "L U' B' U' B U' R' U' R",
        "L' R' B L U' R B' R' U'",
        "R' B' L' B L B R' B' R'",
        "R' L R' U' B' U' B U R'",
        "U R' L R' L' U' L' R L R",
        "U R' L R' L' R B U B' U'",
        "U' R B' R L' R' U R B L'",
        "U' R L' R U' R' L' R' U' L'",
        "B U R U' L' U B' U R' L'",
        "B U R' B' U R' B L' B' L",
        "B R U' B' U' R' U L R' L",
        "B R U' R' B' U' L' R U L",
        "B R' B' R L R' B' L B R'",
        "B R' L' U' B L' U B U R'",
        "B' L' R' B L R B L R' B'",
        "L B' U R U B' U' B' R U'",
        "L R' U B' R' B' R U R B'",
        "L R' U' B' U R' L B U' L"
    ],
    "88": [
        "B' L' R' U L' B U R' L'",
        "R B' L' B' L R' L' B' L",
        "R B' R' L U R U' L B",
        "R' U' L' U L U R' U' R'",
        "R' U' L' U R' B' L' B L",
        "R' B L R' L' B' R' L R'",
        "U B' U R' L' B U R U' L'",
        "U' L R L U' B' R' B R' L",
        "U' L' B L U R L B' R' U'",
        "B L' R B L' B' L B' L' R",
        "B' U' L' U B L' R' L' R' L'",
        "B' L R' L' R' U B L U' L",
        "B' R' L R L U' L' U L' B",
        "L U' B' R L' B U' L' R U",
        "L B U L R B' L' U' R' L'",
        "L B U R' B' U' L' R' L U",
        "L B' R L B' R L' B' R' L",
        "L B' R' U' L' U R B R L'",
        "L R' L B U' B' U' R' L U",
        "L' U B R B' R' B L' U B'"
    ],
    "89": [
        "U' L' R B' L' U' B U L'",
        "L B R B' R' B' L B L",
        "L R' L U B U B' U' L",
        "R L B' R' U L' B L U",
        "R' U B U B' U L U L'",
        "R' U' L U L B' L B L",
        "U L' B L' R L U' L' B' R",
        "U L' R L' U L R L U R",
        "U' L R' L R U R L' R' L'",
        "U' L R' L R L' B' U' B U",
        "B R L B' R' L' B' R' L B",
        "B' U' L B U' L B' R B R'",
        "B' U' L' U R U' B U' L R",
        "B' L B L' R' L B R' B' L",
        "B' L R U B' R U' B' U' L",
        "B' L' U B U L U' R' L R'",
        "B' L' U L B U R L' U' R'",
        "L U L R B' L' U' R' B L'",
        "L U R U L U' R U' L R",
        "L U R' B' L B R U' R' L'"
    ],
    "90": [
        "U B U' B' R B' R' B",
        "U' B L R' L R L' B'",
        "U B' L U' R' L B L R",
        "U' B L R B' R' L R L",
        "L U L' U' L B R B' L",
        "L' R' U' L' B U R' L B'",
        "R' U R' U' R' B U B' R'",
        "R' L' R' L U R' B' R' B",
        "U B L B R' B' R B' L' U'",
        "U B' U' L B L' R L' U' R",
        "U L B' U L R L' U B U",
        "U L' R' L B L' R U B' L'",
        "U R' L U' B' R' L R U' B",
        "U' B U' B L' U' B U R' L",
        "U' B L B R' B' L R B' L'",
        "U' B L B' L R B' L' B L'",
        "U' B L' B R' L R L' R' B",
        "U' B R B' L' B L' B R' B",
        "U' B' L B L' U' R L U' R",
        "U' L' R' U' B L' B U L B"
    ],
    "91": [
        "U B' R' L R' L' R B",
        "U' B' U B L' B L B'",
        "U B' R' L' B L R' L' R'",
        "U' B R' U L R' B' R' L'",
        "L U' L U L B' U' B L",
        "L R L R' U' L B L B'",
        "R L U R B' U' L R' B",
        "R' U' R U R' B' L' B R'",
        "U B R' B' R U L' R' U L'",
        "U B' U B' R U B' U' L R'",
        "U B' L' B R B' R B' L B'",
        "U B' R B' L R' L' R L B'",
        "U B' R' B R' L' B R B' R",
        "U B' R' B' L B R' L' B R",
        "U L B R U' R' U R' B' U'",
        "U L' B U B' U' B' U L' B",
        "U R L U B' R B' U' R' B'",
        "U R L R B' U' B R' U' R'",
        "U' B U R' B' R L' R U L'",
        "U' B' R' B' L B L' B R U"
    ],
    "92": [
        "U' R' U B L B' U' R",
        "B U' R' L' B' U L R",
        "L' B L B' U' B' U B",
        "L' R' B' R B R L U'",
        "U' R B R B' R' U' L' U'",
        "B U B U R L' R' U' B",
        "R B R' L' B' U L' R' L'",
        "R L R B' R B R U' L'",
        "U B' L' B' L U R L R' B'",
        "U L' U' B' R' B L B' R B",
        "U R B' L' U' B' L R L B'",
        "U R B' L' R' U' L' B R L",
        "U R L B R' U L B' R U",
        "U R' B' R' L' U' L B R L",
        "U' B' L' U' B U B' L U B",
        "U' B' R L' R' B U B U B'",
        "U' L U' R B R' U B' R U'",
        "U' L' U R U L U' L R' L'",
        "U' R' L' U B' L R U B U'",
        "U' R' L' U B' R' L U R B"
    ],
    "93": [
        "U L U' B' R' B U L'",
        "B' U L R B U' R' L'",
        "R B' R' B U B U' B'",
        "R L B L' B' L' R' U",
        "U L' B' L' B L U R U",
        "B' U' B' U' L' R L U B'",
        "L' B' L R B U' R L R",
        "L' R' L' B L' B' L' U R",
        "U B L' R L B' U' B' U' B",
        "U B R U B' U' B R' U' B'",
        "U L R U' B L R' U' L' B'",
        "U L R U' B R' L' U' B' U",
        "U L R L U' L' U' R' U L'",
        "U R U' L' U' R' U R' L R",
        "U R' U L' B' L U' B L' U",
        "U' B R B R' U' L' R' L B",
        "U' L B L R U R' B' L' R'",
        "U' L' B R U B R' L' R' B",
        "U' L' B R L U R B' L' R'",
        "U' L' R' B' L U' R' B L' U'"
    ],
    "94": [
        "L' U' L B U L U' B'",
        "L' R L R' U' R' U R",
        "B' L' U' L' U L B' U B'",
        "L U' B' U B L R' U R",
        "U B U L' U' L' U L U' B'",
        "U B U' B U B' L' U B' L'",
        "U B' U L' R L' U' L' R B",
        "U B' L' U B' L' U B U' B",
        "U L B R' U' B L' R' L' B",
        "U R' U' R L U' L' R' U R",
        "U R' U' R L B L B' L' U'",
        "U R' B U B' U' B' R B U'",
        "U' B' U B L' U' L' U L U",
        "U' B' R' B R L U L' R' U",
        "U' L B L' B' U L' R' U R",
        "U' L' U B' L' B' U B U B",
        "U' R' U' R' U R U L' R L",
        "B U B U' B' L' U' B' U L",
        "B U B' U' L' U B' L' U B",
        "B U B' L' U' B' L' B U L"
    ],
    "95": [
        "R U R' B' U' R' U B",
        "R L' R' L U L U' L'",
        "B R U R U' R' B U' B",
        "R' U B U' B' R' L U' L'",
        "U B U' B' R U R U' R' U'",
        "U B L B' L' R' U' R L U'",
        "U L U L U' L' U' R L' R'",
        "U R U' B R B U' B' U' B'",
        "U R' B' R B U' R L U' L'",
        "U' B U' R L' R U R L' B'",
        "U' B R U' B R U' B' U B'",
        "U' B' U B' U' B R U' B R",
        "U' B' U' R U R U' R' U B",
        "U' L U L' R' U R L U' L'",
        "U' L U L' R' B' R' B R U",
        "U' L B' U' B U B L' B' U",
        "U' R' B' L U B' R L R B'",
        "B L B R' B' L' R B' L' U",
        "B L' R U' B U R L U B",
        "B R L' R' L R' U' R U B'"
    ],
    "96": [
        "B U L' U' B' L' U L",
        "R' U' R U R L' R' L",
        "B U' B L' U' L U L B",
        "R' U' R L' B' U' B U L'",
        "U B' R' B U B U' B' R U'",
        "U B' R' B R U' L U L' R'",
        "U L B L' B' L' R' U R U'",
        "U L' R' L' B' U B L U' R",
        "U R' B' L R' B' L' B R B",
        "U' B U R' L U B' R' L R'",
        "U' L' U' L U L B' U' B U",
        "U' L' U' L B L B' L' U L",
        "U' R L U' L' U L U L' R'",
        "U' R L U' L' R' B' R B U",
        "U' R' U' L B R L' R B' R",
        "U' R' B U' R' L U B' L R",
        "U' R' L U L R' L B U' B'",
        "B U B' U' B' L' U' B U L",
        "B U L R' U R' B' U' R L'",
        "B U L' U' L U L U' B' U'"
    ],
    "97": [
        "B' U' R U B R U' R'",
        "L U L' U' L' R L R'",
        "B' U B' R U R' U' R' B'",
        "L U L' R B U B' U' R",
        "U B' U' L R' U' B L R' L",
        "U L U R' B' L' R L' B L'",
        "U L B' U L R' U' B R' L'",
        "U L R' U' R' L R' B' U B",
        "U L' R' U R U' R' U' R L",
        "U L' R' U R L B L' B' U'",
        "U R U R' U' R' B U B' U'",
        "U R U R' B' R' B R U' R'",
        "U' B L B' U' B' U B L' U",
        "U' B L B' L' U R' U' R L",
        "U' L B R' L B R B' L' B'",
        "U' R L R B U' B' R' U L'",
        "U' R' B' R B R L U' L' U",
        "B U B U B' R' B' U R' U'",
        "B U R' B' U R' U' B' U B",
        "B U' B U R' B' U R' B' U"
    ],
    "98": [
        "U L R B U' R' L' B'",
        "U' B' U' L' R L U B",
        "U B L' R U B' L R' L",
        "U L' U R U R' U' L U",
        "U L' B' R L' U R B R",
        "B R B' R' B U B U' B",
        "B' U L' B L U' R U L",
        "L B U B' L U R' L U'",
        "L R' L U' R L B' R B",
        "R U B R U' B R' U' B",
        "U L B' U' R' B U B L' B'",
        "U L R B R U' L' R' B' L'",
        "U L R' U B' U' L' R L' B",
        "U R U R B' L' R L B R",
        "U R B U' B R L' R L B",
        "U R' U' R' B U L U L' B'",
        "U R' B U' R' L' B L' U B",
        "U' B' U' L' U R U L B L'",
        "U' B' L B R U R' B' L' B",
        "U' B' L R U L B R' L' R'"
    ],
    "99": [
        "B L R U B' R' L' U'",
        "B' U' L' R' L U B U",
        "U L' R U' L' B U' B' L'",
        "U' L' U R U' R' U' L U'",
        "B' U B' U' B' R B R' B'",
        "B' U R B' U R' B' U' R'",
        "B' R' B L' R' U L' R L'",
        "L' U' R' U L' B' L U' B",
        "L' R L' B U' R' L B' U'",
        "R' B' R' U' L R' B L U'",
        "U B U B L' R' L B' U' B'",
        "U B L B' U' B' R' U B L'",
        "U L B L U' B' R' U R' L'",
        "U L R B R L' R' B' R' L'",
        "U L R B R' L' B' L' R' L",
        "U' B' U' L' U B U L R L'",
        "U' B' U' L' U' B L U R L",
        "U' L' B' R' L R B L R' U",
        "U' R U' B' R' L B L R L'",
        "U' R B L' B' L' U' R L R"
    ],
    "100": [
        "U' R' U' L U L' U R",
        "R B R' B U B' U' B'",
        "U' L B R B' R' L U R",
        "U' R U' R' B U' B' R U'",
        "B' U L' U R B U' L R",
        "B' L R' L' R L' B' U B'",
        "R B R U' L' R L R B'",
        "R L B' R B L R' L U'",
        "U B U' L' R B U' L' B R'",
        "U B R' U' R' U R' B R' B",
        "U B' R U' L U' L' U' R B",
        "U L' R' L R' U' R U R U'",
        "U R' L' R B U L' R U' B'",
        "U' B L' R B R' U' L B R'",
        "U' B R U B R' U' B R' U'",
        "U' L U L R' B U R' B' L'",
        "U' L B' R L U' B' U B' R",
        "U' L' R B' L' B L R' U R",
        "U' L' R' L U R' U' R U R",
        "U' R U' B' R B U' R U' R"
    ],
    "101": [
        "U L U R' U' R U' L'",
        "L' B' L B' U' B U B",
        "U L' U L B' U B L' U",
        "U R' B' L' B L R' U' L'",
        "B U' R U' L' B' U R' L'",
        "B R' L R L' R B U' B",
        "L' B' L' U R L' R' L' B",
        "L' R' B L' B' R' L R' U",
        "U B' L' U' B' L U B' L U",
        "U B' R L' B' L U R' B' L",
        "U L R' B R' L' R' U R B'",
        "U L' U B L' B' U L' U L'",
        "U L' U L' U L' R L R' L'",
        "U L' B' L' U' R U' R B R",
        "U R L R' U' L U L' U' L'",
        "U R L' B R B' R' L U' L'",
        "U R' U' R' L B' U' L B R",
        "U R' B L' R' U B U' B L'",
        "U' B L' U R' U R U L' B'",
        "U' B' U R L' B' U R B' L"
    ],
    "102": [
        "R' U R' L U L U R' L",
        "U L' U B R' L' B R' U' B",
        "U R L B L U' B R U' B",
        "U R L' U L R' U' L' U' L",
        "U' L U R B R' L B' R' U'",
        "U' L' U' B' U B' R' B' L U'",
        "B L' R B' L' R L U L' R'",
        "B R U R U L U R B' U'",
        "B R' B' R' L B' R B R U'",
        "B' L R' B' L U B' U R U'",
        "B' R U' R' B R' U' L R U",
        "B' R B R U' L' U L R' U'",
        "B' R' L R' L B R' U R' U",
        "L U' R' U L' R' U' R U R",
        "L B U B' R' L' R U' R' U",
        "L B L R' B L' B' L' U B'",
        "L B' U' B U R' B' L R' B",
        "L R L' R' U' L R' L' U R",
        "L' U' B' U L' U R U' L B",
        "L' U' B' L' U' L' B U R' L'"
    ],
    "103": [
        "L U' L R' U' R' U' L R'",
        "U R U B U' B L B R' U",
        "U R' U' L' B' L R' B L U",
        "U' L' R U' R' L U R U R'",
        "U' L' R' B' R' U B' L' U B'",
        "U' R U' B' L R B' L U B'",
        "B L R' L R' B' L U' L U'",
        "B L' U L B' L U R' L' U'",
        "B L' B' L' U R U' R' L U",
        "B R' L B R' U' B U' L' U",
        "B' L B L R' B L' B' L' U",
        "B' L' U' L' U' R' U' L' B U",
        "B' R L' B R L' R' U' R L",
        "L' B L R' U R' L U' L B'",
        "L' B R U' L U' B R' B R'",
        "L' R B' L' R L U L' R' B",
        "L' R B' R' L' B L R' U R",
        "L' R' L' R' B U R U R B'",
        "R U B U' R U' L' U R' B'",
        "R U B R U R B' U' L R"
    ],
    "104": [
        "L' R U' L' U' L' R U' R",
        "U B R' U' L' U' R' U' R' B'",
        "U L' B R B U' B U L U",
        "U R B L' R B' R' U' L' U",
        "U R L' U' L U R' B' R' B",
        "U R' U' B U' L' B R L' B",
        "U R' B' R' B L' R B R B'",
        "U' R U R' L R B U' B' L'",
        "U' R U' R B' L' R L' R B",
        "U' R' L' U R B' R U R' B",
        "B U' B' L U R U L U L",
        "B U' L B L B' R L' B' L'",
        "B L' R' U R L R' B' L R'",
        "B' U R B' L R B' U' L U'",
        "B' U R' B' U L' B' L' R' U'",
        "B' L U L U B L' R' L' R'",
        "B' L' U R' U' L U' B U L",
        "B' R U' R L' U L' R B R'",
        "B' R L' B R U' B' U B L'",
        "L U L' R B R' L' B' L R'"
    ],
    "105": [
        "R L' U R U R L' U L'",
        "U L R U' L' B L' U' L B'",
        "U L' U L' B R L' R L' B'",
        "U L' U' L R' L' B' U B R",
        "U' B' L U R U L U L B",
        "U' L U B' U R B' L' R B'",
        "U' L B L B' R L' B' L' B",
        "U' L' B' R L' B L U R U'",
        "U' L' R U R' U' L B L B'",
        "U' R B' L' B' U B' U' R' U'",
        "B U' L B U' R B R L U",
        "B U' L' B R' L' B U R' U",
        "B L' U L' R U' R L' B' L",
        "B L' R B' L' U B U' B' R",
        "B R U' L U R' U B' U' R'",
        "B R' U' R' U' B' R L R L",
        "B' U B R' U' L' U' R' U' R'",
        "B' U R' B' R' B L' R B R",
        "B' R L U' L' R' L B R' L",
        "L U L U' L' R' U L' U' R"
    ],
    "106": [
        "R' L U B U B R' U' B",
        "U B L B R' B R U R' U",
        "U B' U' B' R' B' U L U L",
        "U B' L U R B' L U' R' B'",
        "U R U' L' B L B' L U' R'",
        "U R L' R U R B' R U B",
        "U R' L B U' R' L' U B' R",
        "U' B R' U B L' U' R U' B",
        "U' B' L U' L' R L' U B R",
        "U' B' R B R B' U B L' R'",
        "U' L' R U' B L R B' U R'",
        "U' R U B R B' U R' U' L'",
        "U' R L U R B R' B L B",
        "U' R L' B' L U' R L B L'",
        "B U' B' U R' L R' U L' U",
        "B L U R' L B' L' U R' L'",
        "B L R' U L' U' R L B' U'",
        "B L' R' U' R' L B U' L B",
        "B R B' L B' U B' R' B' L",
        "B R' B' L B L' U B' R' U"
    ],
    "107": [
        "U L' B' R L U L R L'",
        "U B U R' B U R U R U'",
        "U B L' R U L' B' L' B' R",
        "U B R' L U' L' R L' B L'",
        "U L U L' U B U R' B U",
        "U L' B L' R' L U L' B U'",
        "U L' B R B R' L' B' U' B",
        "U R' B U' B' R U R' U B'",
        "U' R L' U' B U B L' U R'",
        "U' R' U' B R' L B R L' U",
        "B U' R' B' R U' L B' L R",
        "B L B U' R L U' R' U' R'",
        "B L R B U' L' R' U' L' U",
        "B R' B U B' R' B' L B' L",
        "B' U B R B' U R' U' R U'",
        "B' U L' U' R' U' R' U R' L'",
        "B' L' U' R U' R' U' R' L' R",
        "B' L' B' L U' R L B R U'",
        "B' R' U B L U R' L B' L'",
        "B' R' U R' U' R B' U B R"
    ],
    "108": [
        "L R' U' B' U' B' L U B'",
        "U B L' B' L' B U' B' R L",
        "U B R' U R L' R U' B' L'",
        "U B' L U' B' R U L' U B'",
        "U L' U' B' L' B U' L U R",
        "U L' R B R' U L' R' B' R",
        "U L' R' U' L' B' L B' R' B'",
        "U R L' U B' R' L' B U' L",
        "U' B U B L B U' R' U' R'",
        "U' B R' U' L' B R' U L B",
        "U' B' R' B' L B' L' U' L U'",
        "U' L R' B' U L R U' B L'",
        "U' L' U R B' R' B R' U L",
        "U' L' R L' U' L' B L' U' B'",
        "B U L B U' B' R B' U' R'",
        "B U' B L' U' B' R B L' B",
        "B L' B L B' R L U' B' L'",
        "B R' B' R' L B' U' L B L",
        "B' U B U' L R' L U' R U'",
        "B' L B R' B' R U' B L U'"
    ],
    "109": [
        "U' R B L' R' L' B' R' L",
        "U R L B' R B' U' R' L B'",
        "U R' U L U' L' R' U R' U",
        "U' B L' U R L' R' U B' R",
        "U' L' U' R U' L' B' L' U' B",
        "U' L' B R' B R B' R B' L",
        "U' L' R U' B' L U L B U'",
        "U' R B' L U R' U' L R' B",
        "U' R B' R' L' R L R B R'",
        "U' R' B' R U' B' R' U R' B'",
        "B U' B' R L' B U B' R' L",
        "B U' L' B L B' U' L B' R",
        "B L B' R' L B R' U B' U'",
        "B' U B' U' B U' B L' R L",
        "B' U B' L' B L R B L' R'",
        "B' U B' R' L' B R' B' L' B'",
        "B' U R U' B U' R' U R U'",
        "B' U R L U R' U' B L' R'",
        "B' L B' R U' R B' U L U'",
        "B' R L U' B' L' B L' B L"
    ],
    "110": [
        "U' B' L U R U L U' L",
        "U' L U R L R' B R' B",
        "B U' L R U' B' U' B' L'",
        "R L U' R' B R B U' R",
        "U L' B U R U' B' L U' B'",
        "U L' B' R' L R L' R U' R",
        "U L' R' B R L' B L' U L'",
        "U R U' R B R L' B R L",
        "U R' U B L' U R' L' B U'",
        "U R' L' R' B' R U R L' U",
        "U' B U' L' U R U' B R' L",
        "U' B L B L' U' B' R' B L",
        "U' B' U' B' U L R B U L'",
        "U' L' U L R' B R B' R B'",
        "U' L' B U' R U B' L U B'",
        "B U' R' L U' B L R' L U'",
        "B L U' B' U R' U L B' L'",
        "B L' U R' U' L U' B U' L",
        "B L' R U R' U' B' U B' U",
        "B R U L' R' L' U' B R' U"
    ],
    "111": [
        "U B L' R' L R B R' B",
        "B' L' R U R L B L' U",
        "B' R U R U B' L B' L",
        "L B' R L B' R' B' R' U'",
        "U B L' R' U' L' U R L B'",
        "U B R' U' L U' B' L U R'",
        "U B' R' L U R U' R' L' B",
        "U' B U L R' L R L' U' B'",
        "U' L U B U' R' L B' U' R",
        "U' L' U' B' U R U' B U L",
        "B U L' R U R B' L R U",
        "B U' L' R' B' L B L B' R",
        "B U' R U B' R B' U' B R'",
        "B R' U L R B' U' L R' L'",
        "B R' U' B' R U B' U R' B",
        "B R' B' U B R' B U' B U'",
        "B' L B' R' L R B' U R' U",
        "B' L R B U' B' R' L' B U",
        "B' L' B' L' B R L R B U'",
        "B' R' U L' U R U' B R L'"
    ],
    "112": [
        "U B' U' B' R' L B' U L'",
        "U R B' U' B' U' L' R B'",
        "B' R' B L B' U' R' B U'",
        "L' U B' L' R U R L B",
        "U B U' R' L B' U' R U' L",
        "U B R' U R' B' L U' R' L",
        "U R U B L' B' R' B' R' B",
        "U R' U L B' U' R B' U B'",
        "U R' B' R' B U B U L' B'",
        "U' L U B' R' U R' U R' B",
        "U' L R U R' B' R U' B U'",
        "U' L R' B' U' R B L' R L",
        "U' R B R L R' L' B' U R'",
        "U' R L' R' U R' U L U' R",
        "U' R' B R' U' R' L R' U' B'",
        "B L' U' B' L B' U' B R U",
        "B R B R U' B' R L' B' L'",
        "B R' B' U' R L B' R B R'",
        "B' R B R' L' B' U B R U'",
        "B' R' U L B' U L R' B' R"
    ],
    "113": [
        "U B R' U' L' U' R' U R'",
        "U R' U' L' R' L B' L B'",
        "B' U R' L' U B U B R",
        "L' R' U L B' L' B' U L'",
        "U B U B U' R' L' B' U' R",
        "U B' U R U' L' U B' L R'",
        "U B' R' B' R U B L B' R'",
        "U R U' R' L B' L' B L' B",
        "U R B' U L' U' B R' U' B",
        "U' L U' B' R U' L R B' U",
        "U' L R L B L' U' L' R U'",
        "U' L' U L' B' L' R B' L' R'",
        "U' R B L R' L' R L' U L'",
        "U' R B' U' L' U B R' U B",
        "U' R L B' L' R B' R U' R",
        "B R L' B' R L R B L R",
        "B R' B' L B' L' B L' B R",
        "B' U L R' U B' R' L R' U",
        "B' L' U' R L R U B' L U'",
        "B' L' R B' L' R' L' R' L R'"
    ],
    "114": [
        "U B U' L U L' B' L U' L'",
        "U B' R' B L R' B U B' L'",
        "U B' R' L B' R' B U L' B",
        "U R U B U' L' R' L' B' L",
        "U R' L U L' U' R B' R' B",
        "U' B L B' R' L B' U' B R",
        "U' B L R' B L B' U' R B'",
        "U' B' U R' U' R B R' U R",
        "U' L R' U' R U L' B L B'",
        "U' L' U' B' U R L R B R'",
        "B U B' R' L B' R' B U L'",
        "B U R' L U L' U' R B' R'",
        "B L U' B' U' B' U' L B L",
        "B L' U' R U R' L U B' R'",
        "B L' B' U R' B' U B L' R",
        "B' U' B L R' B L B' U' R",
        "B' U' L R' U' R U L' B L",
        "B' R U L' U' L R' U' B L",
        "B' R B U' L B U' B' R L'",
        "B' R' U B U B U R' B' R'"
    ],
    "115": [
        "U B U' L U' B L' R B",
        "U' B' U R' U B' R L' B'",
        "U L B' L' U L R U B U",
        "U R U L' U' R' U' R' L R",
        "U R' U' B L R L' B' R L'",
        "U R' B' R' L U R' B U L'",
        "U' L U B' R' L' R B L' R",
        "U' L B L R' U' L B' U' R",
        "U' L' U' R U L U L R' L'",
        "U' R' B R U' R' L' U' B' U'",
        "B U' L' R U' L' B' L' R' U'",
        "B L R B L U L' R' U B",
        "B L' U' L' B' U R' U' R' U'",
        "B L' B' L' B U B' U R' L",
        "B R U L B U L' B L U'",
        "B R B U B' L B U B U'",
        "B' U R L' U R B R L U",
        "B' L' U' R' B' U' R B' R' U",
        "B' L' B' U' B R' B' U' B' U",
        "B' R U R B U' L U L U"
    ],
    "116": [
        "U B' L B U L U' R' U' L'",
        "U R' B U' L U B' R' U R'",
        "U' B R' B' U' R' U L U R",
        "U' L B' U R' U' B L U' L",
        "B U R B' R U' R' L' U R'",
        "B U R' U L B' L' R L' U'",
        "B U' B' U' B L U R B' L'",
        "B' U B U B' R' U' L' B R",
        "B' U' L U' R' B R L' R U",
        "B' U' L' B L' U L R U' L",
        "L U' B' U B U' R U' L R'",
        "L B' U R U' B' R L' R B'",
        "L B' L U B L' U R' L' U'",
        "L R' B R' B R' L' R B R'",
        "L' U' L R B L B' U' R' U",
        "L' B' U R' L' B L U L' R",
        "L' B' L' B' R B R L R' B",
        "L' R B' L' R' U B R' U R",
        "R U R' L' B' R' B U L U'",
        "R B U' L R B' R' U' R L'"
    ],
    "117": [
        "B U' B' L' R' U' L R' U",
        "B U' R B' R' L' U' R' U",
        "B' U B R L U R' L U'",
        "B' U L' B L R U L U'",
        "U B' L U' L' R' L' U L B",
        "U L U R' L' R' L' R' U L",
        "U R B' L B R' U' L' R' L",
        "U R L R' B' L' U' L R' B",
        "U R' B U' R' L' U R B' R",
        "U' B R' U R L R U' R' B'",
        "U' L B' U L R U' L' B L'",
        "U' L' B R' B' L U R L R'",
        "U' L' R' L B R U R' L B'",
        "U' R' U' L R L R L U' R'",
        "B U' R B U' B' U R B' L'",
        "B L' B R B U' B' R' B U'",
        "B R' L U L' R' U B' R L'",
        "B R' L' B L R B' R B' R'",
        "B' U L' B' U B U' L' B R",
        "B' L R B' R' L' B L' B L"
    ],
    "118": [
        "U B L' B' R' B' L B",
        "U B R B' L' B' R' B",
        "U R B R' L' B' R' L",
        "U R L' B' R' L' B L",
        "B L' R' B U' R B L'",
        "B R' B L U' B L' R'",
        "B' L' B R B L B' U'",
        "B' R B L B R' B' U'",
        "L B' R' U B' R L B'",
        "L R' U L R' L U' R'",
        "L' B' L R B L R' U'",
        "L' R B L R B' R' U'",
        "R U L' R L' U' R L'",
        "R L B' U L' B' R B'",
        "B U' B' L' B R B L B",
        "B U' B' R B L B R' B",
        "B' L' B' R' B' L B U B'",
        "B' R B' L' B' R' B U B'",
        "L U' B' U L R B R' L",
        "L U' B' L' U R L B L"
    ],
    "119": [
        "U' B' L' B R B L B'",
        "U' B' R B L B R' B'",
        "U' L' B' L R B L R'",
        "U' L' R B L R B' R'",
        "B L' B' R' B' L B U",
        "B R B' L' B' R' B U",
        "B' L B' R' U B' R L",
        "B' R L B' U L' B' R",
        "L' U' R L' R U L' R",
        "L' R' B U' R B L' B",
        "R B R' L' B' R' L U",
        "R L' B' R' L' B L U",
        "R' B L U' B L' R' B",
        "R' L U' R' L R' U L",
        "B L' B R B L B' U' B",
        "B R B L B R' B' U' B",
        "B' U B L' B' R' B' L B'",
        "B' U B R B' L' B' R' B'",
        "L U L' R U L' U R' L",
        "L B L' B U R' B U' L"
    ],
    "120": [
        "U B R B U' B' L' B'",
        "U B' R' B' U' B L B",
        "U R B R U' L' B' L'",
        "U R' B' R' U' L B L",
        "B L B U B' R' B' U'",
        "B L B R' B' U' B' R",
        "B' L' B' U B R B U'",
        "B' L' B' R' B U B R",
        "L B L U R' B' R' U'",
        "L B L R' U' B' U' R",
        "L' B' L' U R B R U'",
        "L' B' L' R' U B U R",
        "R' U B U R L' B' L'",
        "R' U' B' U' R L B L",
        "R' B U B R B' L' B'",
        "R' B' U' B' R B L B",
        "B U R B' L R' B' U B",
        "B R B' U' L B' U R B",
        "B' U' B R L' B R' U' B'",
        "B' R' U' B L' U B R' B'"
    ],
    "121": [
        "U B' U' B L R' U' R",
        "U R U' R' B R B' L'",
        "B' U B U' R' U R L'",
        "B' L' U R U' R' B R",
        "U B' L R L' R' U B L' U'",
        "U R L U' B' R B R' L' U'",
        "B' U R' U' L B R' B' R B",
        "B' L' B' U B U' R' U R B",
        "L U B U' R' U R L' B' L'",
        "L U R' U' L B R' B' R L'",
        "L B L B R' U R U B U'",
        "L B L R' B R U R U' B",
        "L B R' U R U B U' L B",
        "L R' U' L' U' L R' L' R' U'",
        "L R' B R U R U' B L B",
        "R' U L' U' L' R' U L' R' U'",
        "R' U R U B U' L B L B",
        "R' B' L' U' B R' L' B' U' B",
        "R' B' L' B U' B' R' L' B U'",
        "R' B' R L' B' L' B' U R' U'"
    ],
    "122": [
        "U B' L' B R B L B' U",
        "U B' R B L B R' B' U",
        "U L' B' L R B L R' U",
        "U L' R B L R B' R' U",
        "U' B L' B' R' B' L B U'",
        "U' B R B' L' B' R' B U'",
        "U' R B R' L' B' R' L U'",
        "U' R L' B' R' L' B L U'",
        "B U' L' R B R L U' B",
        "B U' R L B L R' U' B",
        "B L' B R L R L' R' B",
        "B L' R' L R L B R' B",
        "B' U L' R' B' R' L U B'",
        "B' U R L' B' L' R' U B'",
        "B' R B' L' R' L' R L B'",
        "B' R L R' L' R' B' L B'",
        "L U R L B L' U' B' L",
        "L U' R' B' R U L B L",
        "L R L R U R' U' R' L",
        "L R' B' L' B R L R L"
    ],
    "123": [
        "U B' U B' L' R B' L",
        "U L' U R' L' U L' R",
        "U' B U' B R L' B R'",
        "U' R U' L R U' R L'",
        "B U' B U' L' B R' L",
        "B L' U L' B' R U' R",
        "B' U B' U R B' L R'",
        "B' R U' R B L' U L'",
        "L U' L B' R' U R' B",
        "L R' U R' L' U R' U",
        "L' B R' L B U' B U'",
        "L' R B' L U B' U B'",
        "R B' L R' B' U B' U",
        "R L' B R' U' B U' B",
        "R' U R' B L U' L B'",
        "R' L U' L R U' L U'",
        "U B U' B' L' B' U B R U'",
        "U B U' L U B R U' B L",
        "U B L B' U' B' L' B R U'",
        "U B L R U R L U' R B'"
    ],
    "124": [
        "U' L U' L' R B U' B' U'",
        "U' R' B' L B L' U' L U'",
        "B' U B' R' L U L' U' B'",
        "B' R' L' R L U' B' R B'",
        "R' B' R' B U L' R' L R'",
        "R' L R' L' B L B' U' R'",
        "U R' B U L' R' L R B' U'",
        "U R' L' B L B' U' R L U'",
        "U' L B L' U' L U R' B' U",
        "U' R' L U L' U' B U B' U",
        "B L' U L B' L' B R U' B'",
        "B L' R' U B L' B' L R B'",
        "B' U L B' L' B R U' L' B",
        "B' R' U B L' B' L R L' B",
        "R B' U' R L R' L' B L R'",
        "R B' R B R' L' R L U' R'",
        "R' B' U L U' L' R B U' R",
        "R' L U R' B' L B L' U' R",
        "U B U L U L' B R B R U",
        "U B R' L' B' U' B R' B' L' U"
    ],
    "125": [
        "U L' R B U' B' U L U",
        "U R U B' U' B L R' U",
        "L U L B' L' B R U' L",
        "L R' U B L' B' L R L",
        "R U' L B R' B' R U R",
        "R L R B' R' B U L' R",
        "U L' U' L U R' B' L B U'",
        "U R B' L' U R U' R' B U'",
        "U' B L' U' L U R' B' L U",
        "U' B R B' L' U R U' R' U",
        "L U B' R' L U L' U' B L'",
        "L R' L' R L U' B' R B L'",
        "L' B U B' R' L U L' U' L",
        "L' B R' L' R L U' B' R L",
        "R U' R' U R L' B' U B R'",
        "R L B' U' R L R' L' B R'",
        "R' B U' R' U R L' B' U R",
        "R' B L B' U' R L R' L' R",
        "U B R' B L B' L' B U B R'",
        "U B' L R' L B' U B U B L'"
    ],
    "126": [
        "U' B U' B L B U' R U' R'",
        "U' R U' L R L R' L U' R'",
        "B U L' B U R' L' B U' L'",
        "B U' L' B U' R' L B U' L",
        "L B U' R U' R' U' B U' B",
        "L B R' B R' U' R' U R' B",
        "R U' B' U R' L' U B U' L",
        "R B L' R B L' R' B L' U'",
        "R' B L' U' R B L' R B L'",
        "R' B L' R' B L R' B L U'",
        "U B' U L' R' U' B R' L' R' L",
        "U B' L' U L U R' L B L R'",
        "U L U L U' B' R' L B L R'",
        "U L R' U' B' U' R' L' B U R'",
        "U L' U B R' L' U' B' U' L' R",
        "U L' U' L U' B R B U' B U",
        "U L' U' R L' R L R U' L U",
        "U L' R B R L' U R U R' B'",
        "U L' R B R L' B' U' R U R",
        "U R L' R' L' B U' L' R' U B'"
    ],
    "127": [
        "U B' U B' R' B' U L' U L",
        "U L' U R' L' R' L R' U L",
        "B' U R B' U L R' B' U R'",
        "B' U' R B' U' L R B' U R",
        "L B' R U L' B' R L' B' R",
        "L B' R L B' R' L B' R' U",
        "L' U B U' L R U' B' U R'",
        "L' B' R L' B' R L B' R U",
        "R' B' U L' U L U B' U B'",
        "R' B' L B' L U L U' L B'",
        "U B L B' U L' R B U' B' L",
        "U B L' B U' R L' B U' L R",
        "U B' U L' B R' B' R' U' B R'",
        "U B' R U' L' B' R' B' U R L'",
        "U B' R' B' U' B' R U' L' U L",
        "U L B' L U' L' R U R B L'",
        "U L' U' B U' B' R' U' R' U L",
        "U L' U' B U' R U' R' U' B' L",
        "U L' B U' R L' B U' B L R",
        "U L' R U R' L B R' L R B'"
    ],
    "128": [
        "U' L U' R' B' R U' R B R",
        "L' R B' R' L' U L' R B R",
        "R U B U' R U' B' U' R L'",
        "R U B R' B R' L' B' R B'",
        "U B L' B' R' U R' B U' L' B'",
        "U B' U R U' R U' B' R' B' L'",
        "U B' R' U' B L' U L' B' R' B",
        "U L B L U' L B' L' U' R U",
        "U L B' U R B R L' R' U L'",
        "U L' U R L U' R' U L U L'",
        "U R' U L' R' L B L U B' R",
        "U R' U R U L' U' R L U R'",
        "U R' B' L' B' U' L U' L U B'",
        "U' B L B' R L' B R' U' R' B'",
        "U' B R' B U' B R' L U L R",
        "U' B' U' L U' L' U' R U B L'",
        "U' B' L' R L' B R' U' B' R B",
        "U' L U' L R' B L U L B' L",
        "U' L B R' U R' U L B' R L",
        "U' L' U L' U R' B' R' U' B R"
    ],
    "129": [
        "U R' U L B L' U L' B' L'",
        "L' U' B' U L' U B U L' R",
        "L' U' B' L B' L R B L' B",
        "R L' B L R U' R L' B' L'",
        "U B U R' U R U L' U' B' R",
        "U B R L' R B' L U B L' B'",
        "U B' L B' U B' L R' U' R' L'",
        "U B' R' B L' R B' L U L B",
        "U L B' U L U' R U' R B R'",
        "U L' B' U B' R L R L R B'",
        "U L' B' L U' R' B U' R' U L'",
        "U R U' R U' L B L U B' L'",
        "U R U' R L U B U L' B' L'",
        "U R L R U' R L' U B' R' B",
        "U R' U R' L B' R' U' R' B R'",
        "U R' B' L U' L U' R' B L' R'",
        "U' B U' L' U L' U B L B R",
        "U' B L U B' R U' R B L B'",
        "U' B' R B L U' L B' U R B",
        "U' L U' L' U' R U L' R' U' L"
    ],
    "130": [
        "U B' L' B' U B' U R U R'",
        "U' R B L' R' U L' B' R L",
        "U' R L B' R' U L' R' B L",
        "L U B' L' U B' L' R U B'",
        "L R U' B' L U' B' L U B'",
        "R' B U B R' L R' L' R' B",
        "U B U R' L U' R U' L U B'",
        "U B R B U' R L R' L' R' B",
        "U B' U R' L B U L U' L R'",
        "U B' L U' B' L U L R U B'",
        "U B' L' B' U B U' R U R B",
        "U L U L R' U B U R' B' L'",
        "U L' B R' U' L B' L U R L",
        "U L' R B' L' B' U R L' U' B'",
        "U L' R' L U' R' L' R' B R B'",
        "U R B R U L B' R' U R' L'",
        "U R B' U' B' L' R' U B' R L'",
        "U R B' L R' B U L U' L' R",
        "U R L' U R' B L B' R L R'",
        "U R' L U' L R L B' L' B R"
    ],
    "131": [
        "U L' B' R L U' R B L' R'",
        "U L' R' B L U' R L B' R'",
        "U' B R B U' B U' L' U' L",
        "L B' U' B' L R' L R L B'",
        "R' U' B R U' B R L' U' B",
        "R' L' U B R' U B R' U' B",
        "U B' U L U' B R L R U' L'",
        "U B' U L' R L R L' U' B R",
        "U B' R L' U R B' U' B' L' R'",
        "U B' R' L' U B' U R' U B' R'",
        "U L B U' R U' B R' L' B L",
        "U L B U' R' L R L R' U B'",
        "U L B L' U B L B R' L' R'",
        "U L B L' U R' L' B R B R'",
        "U L' B L B R' L' U R' B R",
        "U L' B' U L' U B' U R' L' B'",
        "U L' R' B' U' B' L U R' L B'",
        "U L' R' L' B R B U R' B R",
        "U R U' R' U' B U' B L B U",
        "U R U' R' U' B L B U B L'"
    ]
};